// 
// Decompiled by Procyon v0.5.36
// 

package com.jagex.jnibindings.runetek6.jagbullet;

import java.util.ArrayList;
import com.jagex.maths.Vector3;

public class B45
{
    public float a;
    public boolean aa;
    public float ab;
    public float ac;
    public Vector3 ad;
    public Vector3 ae;
    public ArrayList af;
    public float ag;
    public float ah;
    public ArrayList ai;
    public float aj;
    public float ak;
    public ArrayList al;
    public boolean am;
    public boolean an;
    public boolean ao;
    public boolean ap;
    public float aq;
    public float ar;
    public boolean as;
    public float at;
    public float au;
    public ArrayList av;
    public float aw;
    public float ax;
    public Vector3 ay;
    public float az;
    public float b;
    public Vector3 ba;
    public Vector3 bb;
    public float bc;
    public float bd;
    public float be;
    public float bf;
    public Vector3 bg;
    public float bh;
    public Vector3 bi;
    public float bj;
    public float bk;
    public float bl;
    public Vector3 bm;
    public Vector3 bn;
    public float bo;
    public float bp;
    public float bq;
    public float br;
    public Vector3 bt;
    public Vector3 bu;
    public float bv;
    public float bw;
    public float bx;
    public float by;
    public float bz;
    public float c;
    public float d;
    public float e;
    public float f;
    public int g;
    public float h;
    public float i;
    public float j;
    public float k;
    public float l;
    public float m;
    public float n;
    public float o;
    public float p;
    public float q;
    public float r;
    public float s;
    public float t;
    public float u;
    public float v;
    public float w;
    public float x;
    public float y;
    public float z;
    
    public B45(final B45 b45) {
        this.ai = new ArrayList();
        this.al = new ArrayList();
        this.af = new ArrayList();
        this.av = new ArrayList();
        this.bq = -4.712389f;
        this.bo = -1.5707964f;
        this.bl = -1.5707964f;
        this.bw = -3.1415927f;
        this.bj = -0.7853982f;
        this.bk = 0.0f;
        this.bh = 1.0f;
        this.bp = 0.0f;
        this.bz = 0.2f;
        this.bc = 0.9f;
        this.be = 0.0f;
        this.g = b45.g;
        this.d = b45.d;
        this.q = b45.q;
        this.j = b45.j;
        this.e = b45.e;
        this.h = b45.h;
        this.s = b45.s;
        this.b = b45.b;
        this.l = b45.l;
        this.w = b45.w;
        this.r = b45.r;
        this.v = b45.v;
        this.y = b45.y;
        this.p = b45.p;
        this.x = b45.x;
        this.u = b45.u;
        this.z = b45.z;
        this.t = b45.t;
        this.m = b45.m;
        this.n = b45.n;
        this.t = b45.t;
        this.m = b45.m;
        this.o = b45.o;
        this.a = b45.a;
        this.f = b45.f;
        this.c = b45.c;
        this.az = b45.az;
        this.ah = b45.ah;
        this.ag = b45.ag;
        this.ai = (ArrayList)b45.ai.clone();
        this.al = (ArrayList)b45.al.clone();
        this.af = (ArrayList)b45.af.clone();
        this.av = (ArrayList)b45.av.clone();
        this.aq = b45.aq;
        this.ap = b45.ap;
        this.ao = b45.ao;
        this.aa = b45.aa;
        this.an = b45.an;
        this.am = b45.am;
        this.as = b45.as;
        this.ac = b45.ac;
        this.at = b45.at;
        this.ab = b45.ab;
        this.aw = b45.aw;
        this.ar = b45.ar;
        this.ax = b45.ax;
        this.au = b45.au;
        this.aj = b45.aj;
        this.ak = b45.ak;
        this.ay = b45.ay;
        this.ad = b45.ad;
        this.ae = b45.ae;
        this.bx = b45.bx;
        this.by = b45.by;
        this.br = b45.br;
        this.bv = b45.bv;
        this.bd = b45.bd;
        this.bm = b45.bm;
        this.bq = b45.bq;
        this.bo = b45.bo;
        this.bl = b45.bl;
        this.bw = b45.bw;
        this.bj = b45.bj;
        this.bk = b45.bk;
        this.bh = b45.bh;
        this.bp = b45.bp;
        this.bf = b45.bf;
        this.bn = b45.bn;
        this.bb = b45.bb;
        this.ba = b45.ba;
        this.bi = b45.bi;
        this.bt = b45.bt;
        this.bz = b45.bz;
        this.bc = b45.bc;
        this.bg = b45.bg;
        this.bu = b45.bu;
        this.be = b45.be;
    }
    
    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder(2000);
        sb.append("--------\n");
        sb.append("\nnumWheels: ");
        sb.append(this.g);
        sb.append("\nsuspensionStiffness: ");
        sb.append(this.d);
        sb.append("\nsuspensionCompression: ");
        sb.append(this.q);
        sb.append("\nsuspensionDamping: ");
        sb.append(this.j);
        sb.append("\nextraWheelRaycastDistance: ");
        sb.append(this.h);
        sb.append("\nwheelSpinRateOnSkid: ");
        sb.append(this.s);
        sb.append("\nmaxSuspensionTravelCm: ");
        sb.append(this.b);
        sb.append("\nmaxSuspensionForce: ");
        sb.append(this.e);
        sb.append("\nfrontStaticFriction: ");
        sb.append(this.l);
        sb.append("\nfrontDynamicFriction: ");
        sb.append(this.w);
        sb.append("\nfrontForwardToLateralFrictionRatio: ");
        sb.append(this.r);
        sb.append("\nrearStaticFriction: ");
        sb.append(this.v);
        sb.append("\nrearDynamicFriction: ");
        sb.append(this.y);
        sb.append("\nrearForwardToLateralFrictionRatio: ");
        sb.append(this.p);
        sb.append("\nwheelRadius: ");
        sb.append(this.x);
        sb.append("\nwheelWidth: ");
        sb.append(this.u);
        sb.append("\nrollInfluence: ");
        sb.append(this.z);
        sb.append("\nvisualRollFactor: ");
        sb.append(this.t);
        sb.append("\nvisualRollSpeed: ");
        sb.append(this.m);
        sb.append("\nvisualRollMaxAngle: ");
        sb.append(this.n);
        sb.append("\nvisualPitchFactor: ");
        sb.append(this.k);
        sb.append("\nvisualPitchSpeed: ");
        sb.append(this.i);
        sb.append("\nvisualPitchMaxAngle: ");
        sb.append(this.o);
        sb.append("\naxlePointX_Crf: ");
        sb.append(this.a);
        sb.append("\naxlePointY_Crf: ");
        sb.append(this.f);
        sb.append("\naxlePointZ_Crf: ");
        sb.append(this.c);
        sb.append("\ntopSpeed: ");
        sb.append(this.az);
        sb.append("\nreverseTopSpeed: ");
        sb.append(this.ah);
        sb.append("\nenginePower: ");
        sb.append(this.ag);
        sb.append("\nAccelerations(speed) : ");
        for (int i = 0; i < this.ai.size(); ++i) {
            sb.append("\n   acc(" + this.al.get(i) + ") = " + this.ai.get(i));
        }
        sb.append("\nReverse accelerations(speed) : ");
        for (int j = 0; j < this.af.size(); ++j) {
            sb.append("\n   acc(" + this.av.get(j) + ") = " + this.af.get(j));
        }
        sb.append("\nmaxTorqueAtLowSpeed: ");
        sb.append(this.aq);
        sb.append("\nfrontAxleIsDriving: ");
        sb.append(this.ap);
        sb.append("\nrearAxleIsDriving: ");
        sb.append(this.ao);
        sb.append("\nfrontAxleIsBraking: ");
        sb.append(this.aa);
        sb.append("\nrearAxleIsBraking: ");
        sb.append(this.an);
        sb.append("\nfrontAxleIsHandBraking: ");
        sb.append(this.am);
        sb.append("\nrearAxleIsHandBraking: ");
        sb.append(this.as);
        sb.append("\nrollingFriction: ");
        sb.append(this.ac);
        sb.append("\ndumbDownSkiddingEffectStrength: ");
        sb.append(this.at);
        sb.append("\ndesiredSkidToSteerAnglesRatio: ");
        sb.append(this.ab);
        sb.append("\nwheelFrictionConstraintStabilityTweak: ");
        sb.append(this.aw);
        sb.append("\nlowEndSteeringFullLockAngle: ");
        sb.append(this.ar);
        sb.append("\nhighEndSteeringSpeed: ");
        sb.append(this.ax);
        sb.append("\nhighEndSteeringFullLockAngle: ");
        sb.append(this.au);
        sb.append("\nsteeringChangeRate: ");
        sb.append(this.aj);
        sb.append("\nmaximumBrakingForce: ");
        sb.append(this.ak);
        sb.append("\ncentreOfMassOffset: ");
        sb.append(this.ay);
        sb.append("\ncentreOfShapeOffset: ");
        sb.append(this.ad);
        sb.append("\ncentreOfWheelsOffset: ");
        sb.append(this.ae);
        sb.append("\nmiddleWheelOffsetFromRear: ");
        sb.append(this.bd);
        sb.append("\ngraphicsPivotOffset: ");
        sb.append(this.bm);
        sb.append("\nleftWheelPretransformZangle: ");
        sb.append(this.bq);
        sb.append("\nrightWheelPretransformZangle: ");
        sb.append(this.bo);
        sb.append("\nfrontAxlePretransformXangle: ");
        sb.append(this.bl);
        sb.append("\nfrontAxlePretransformYangle: ");
        sb.append(this.bw);
        sb.append("\nrearAxlePretransformXangle: ");
        sb.append(this.bj);
        sb.append("\nrearAxlePretransformYangle: ");
        sb.append(this.bk);
        sb.append("\nsteeringScale: ");
        sb.append(this.bh);
        sb.append("\nforkLeanAngle: ");
        sb.append(this.bp);
        sb.append("\nmassScaleForContactResolution: ");
        sb.append(this.bx);
        sb.append("\ninertiaScaleForContactResolution: ");
        sb.append(this.by);
        sb.append("\nmaxLinearVelocity: ");
        sb.append(this.br);
        sb.append("\nmaxAngularVelocity: ");
        sb.append(this.bv);
        sb.append("\nbikeLeanAmount: ");
        sb.append(this.bf);
        sb.append("\nlocalAngularDampings: ");
        sb.append(this.bn);
        sb.append("\norientationCorrectionLimits: ");
        sb.append(this.bi);
        sb.append("\norientationCorrectionLimits_hard: ");
        sb.append(this.bt);
        sb.append("\nblendSpeedToVertical_01: ");
        sb.append(this.bz);
        sb.append("\nblendSpeedToSurface_01: ");
        sb.append(this.bc);
        sb.append("\nlocalAdditionalLAngularDampingsOutsideLimits: ");
        sb.append(this.bg);
        sb.append("\nlocalAdditionalLAngularDampingsOutsideLimits_hard: ");
        sb.append(this.bu);
        sb.append("\norientationCorrectionStrengths: ");
        sb.append(this.bb);
        sb.append("\norientationCorrectionStrengths_hard: ");
        sb.append(this.ba);
        sb.append("\noextraAngularPitchVelocityOnTransformation: ");
        sb.append(this.be);
        sb.append("--------\n");
        return sb.toString();
    }
    
    public B45() {
        this.ai = new ArrayList();
        this.al = new ArrayList();
        this.af = new ArrayList();
        this.av = new ArrayList();
        this.bq = -4.712389f;
        this.bo = -1.5707964f;
        this.bl = -1.5707964f;
        this.bw = -3.1415927f;
        this.bj = -0.7853982f;
        this.bk = 0.0f;
        this.bh = 1.0f;
        this.bp = 0.0f;
        this.bz = 0.2f;
        this.bc = 0.9f;
        this.be = 0.0f;
        this.g = 4;
        this.d = 10.0f;
        this.q = 1.3f;
        this.j = 1.3f;
        this.h = 0.6f;
        this.s = 30.0f;
        this.b = 100.0f;
        this.e = 600000.0f;
        this.l = 5.0f;
        this.w = 3.0f;
        this.r = 1.0f;
        this.v = 3.0f;
        this.y = 2.0f;
        this.p = 1.0f;
        this.x = 0.5f;
        this.u = 0.4f;
        this.z = 0.1f;
        this.t = 0.0f;
        this.m = 0.2f;
        this.n = 0.1f;
        this.k = 0.0f;
        this.i = 0.2f;
        this.o = 0.1f;
        this.a = 0.8f;
        this.f = -0.3f;
        this.c = 1.5f;
        this.az = 40.0f;
        this.ah = 10.0f;
        this.ag = 750000.0f;
        this.ai.clear();
        this.al.clear();
        this.af.clear();
        this.av.clear();
        this.aq = 1.0f;
        this.ap = true;
        this.ao = true;
        this.aa = true;
        this.an = true;
        this.am = true;
        this.as = true;
        this.ac = 0.0f;
        this.at = 0.5f;
        this.ab = 1.5f;
        this.aw = 1.0f;
        this.ar = 0.6f;
        this.ax = 25.0f;
        this.au = 0.3f;
        this.aj = 1.0f;
        this.ak = 1.0f;
        this.ay = Vector3.g;
        this.ad = Vector3.g;
        this.ae = Vector3.g;
        this.bd = 0.0f;
        this.bm = Vector3.g;
        this.bq = -4.712389f;
        this.bo = -1.5707964f;
        this.bl = -1.5707964f;
        this.bw = -3.1415927f;
        this.bj = -0.7853982f;
        this.bk = 0.0f;
        this.bh = 1.0f;
        this.bp = 0.0f;
        this.bx = 1.0f;
        this.by = 1.0f;
        this.br = 1.0E10f;
        this.bv = 1.0E10f;
        this.bf = Float.NaN;
        this.bn = Vector3.g;
        this.bb = Vector3.g;
        this.ba = Vector3.g;
        this.bi = Vector3.g;
        this.bt = Vector3.g;
        this.bz = 0.2f;
        this.bc = 0.9f;
        this.bg = Vector3.g;
        this.bu = Vector3.g;
        this.be = 0.0f;
    }
}
