package com.jagex.jnibindings.runetek6.jagbullet;

import com.jagex.maths.Vector3;
import java.util.ArrayList;

public class B45 {
   public float a;
   public boolean aa;
   public float ab;
   public float ac;
   public Vector3 ad;
   public Vector3 ae;
   public ArrayList af = new ArrayList();
   public float ag;
   public float ah;
   public ArrayList ai = new ArrayList();
   public float aj;
   public float ak;
   public ArrayList al = new ArrayList();
   public boolean am;
   public boolean an;
   public boolean ao;
   public boolean ap;
   public float aq;
   public float ar;
   public boolean as;
   public float at;
   public float au;
   public ArrayList av = new ArrayList();
   public float aw;
   public float ax;
   public Vector3 ay;
   public float az;
   public float b;
   public Vector3 ba;
   public Vector3 bb;
   public float bc = 0.9F;
   public float bd;
   public float be = 0.0F;
   public float bf;
   public Vector3 bg;
   public float bh = 1.0F;
   public Vector3 bi;
   public float bj = -0.7853982F;
   public float bk = 0.0F;
   public float bl = -1.5707964F;
   public Vector3 bm;
   public Vector3 bn;
   public float bo = -1.5707964F;
   public float bp = 0.0F;
   public float bq = -4.712389F;
   public float br;
   public Vector3 bt;
   public Vector3 bu;
   public float bv;
   public float bw = -3.1415927F;
   public float bx;
   public float by;
   public float bz = 0.2F;
   public float c;
   public float d;
   public float e;
   public float f;
   public int g;
   public float h;
   public float i;
   public float j;
   public float k;
   public float l;
   public float m;
   public float n;
   public float o;
   public float p;
   public float q;
   public float r;
   public float s;
   public float t;
   public float u;
   public float v;
   public float w;
   public float x;
   public float y;
   public float z;

   public B45(B45 var1) {
      this.g = var1.g;
      this.d = var1.d;
      this.q = var1.q;
      this.j = var1.j;
      this.e = var1.e;
      this.h = var1.h;
      this.s = var1.s;
      this.b = var1.b;
      this.l = var1.l;
      this.w = var1.w;
      this.r = var1.r;
      this.v = var1.v;
      this.y = var1.y;
      this.p = var1.p;
      this.x = var1.x;
      this.u = var1.u;
      this.z = var1.z;
      this.t = var1.t;
      this.m = var1.m;
      this.n = var1.n;
      this.t = var1.t;
      this.m = var1.m;
      this.o = var1.o;
      this.a = var1.a;
      this.f = var1.f;
      this.c = var1.c;
      this.az = var1.az;
      this.ah = var1.ah;
      this.ag = var1.ag;
      this.ai = (ArrayList)var1.ai.clone();
      this.al = (ArrayList)var1.al.clone();
      this.af = (ArrayList)var1.af.clone();
      this.av = (ArrayList)var1.av.clone();
      this.aq = var1.aq;
      this.ap = var1.ap;
      this.ao = var1.ao;
      this.aa = var1.aa;
      this.an = var1.an;
      this.am = var1.am;
      this.as = var1.as;
      this.ac = var1.ac;
      this.at = var1.at;
      this.ab = var1.ab;
      this.aw = var1.aw;
      this.ar = var1.ar;
      this.ax = var1.ax;
      this.au = var1.au;
      this.aj = var1.aj;
      this.ak = var1.ak;
      this.ay = var1.ay;
      this.ad = var1.ad;
      this.ae = var1.ae;
      this.bx = var1.bx;
      this.by = var1.by;
      this.br = var1.br;
      this.bv = var1.bv;
      this.bd = var1.bd;
      this.bm = var1.bm;
      this.bq = var1.bq;
      this.bo = var1.bo;
      this.bl = var1.bl;
      this.bw = var1.bw;
      this.bj = var1.bj;
      this.bk = var1.bk;
      this.bh = var1.bh;
      this.bp = var1.bp;
      this.bf = var1.bf;
      this.bn = var1.bn;
      this.bb = var1.bb;
      this.ba = var1.ba;
      this.bi = var1.bi;
      this.bt = var1.bt;
      this.bz = var1.bz;
      this.bc = var1.bc;
      this.bg = var1.bg;
      this.bu = var1.bu;
      this.be = var1.be;
   }

   public String toString() {
      StringBuilder var1 = new StringBuilder(2000);
      var1.append("--------\n");
      var1.append("\nnumWheels: ");
      var1.append(this.g);
      var1.append("\nsuspensionStiffness: ");
      var1.append(this.d);
      var1.append("\nsuspensionCompression: ");
      var1.append(this.q);
      var1.append("\nsuspensionDamping: ");
      var1.append(this.j);
      var1.append("\nextraWheelRaycastDistance: ");
      var1.append(this.h);
      var1.append("\nwheelSpinRateOnSkid: ");
      var1.append(this.s);
      var1.append("\nmaxSuspensionTravelCm: ");
      var1.append(this.b);
      var1.append("\nmaxSuspensionForce: ");
      var1.append(this.e);
      var1.append("\nfrontStaticFriction: ");
      var1.append(this.l);
      var1.append("\nfrontDynamicFriction: ");
      var1.append(this.w);
      var1.append("\nfrontForwardToLateralFrictionRatio: ");
      var1.append(this.r);
      var1.append("\nrearStaticFriction: ");
      var1.append(this.v);
      var1.append("\nrearDynamicFriction: ");
      var1.append(this.y);
      var1.append("\nrearForwardToLateralFrictionRatio: ");
      var1.append(this.p);
      var1.append("\nwheelRadius: ");
      var1.append(this.x);
      var1.append("\nwheelWidth: ");
      var1.append(this.u);
      var1.append("\nrollInfluence: ");
      var1.append(this.z);
      var1.append("\nvisualRollFactor: ");
      var1.append(this.t);
      var1.append("\nvisualRollSpeed: ");
      var1.append(this.m);
      var1.append("\nvisualRollMaxAngle: ");
      var1.append(this.n);
      var1.append("\nvisualPitchFactor: ");
      var1.append(this.k);
      var1.append("\nvisualPitchSpeed: ");
      var1.append(this.i);
      var1.append("\nvisualPitchMaxAngle: ");
      var1.append(this.o);
      var1.append("\naxlePointX_Crf: ");
      var1.append(this.a);
      var1.append("\naxlePointY_Crf: ");
      var1.append(this.f);
      var1.append("\naxlePointZ_Crf: ");
      var1.append(this.c);
      var1.append("\ntopSpeed: ");
      var1.append(this.az);
      var1.append("\nreverseTopSpeed: ");
      var1.append(this.ah);
      var1.append("\nenginePower: ");
      var1.append(this.ag);
      var1.append("\nAccelerations(speed) : ");

      int var2;
      for(var2 = 0; var2 < this.ai.size(); ++var2) {
         var1.append("\n   acc(" + this.al.get(var2) + ") = " + this.ai.get(var2));
      }

      var1.append("\nReverse accelerations(speed) : ");

      for(var2 = 0; var2 < this.af.size(); ++var2) {
         var1.append("\n   acc(" + this.av.get(var2) + ") = " + this.af.get(var2));
      }

      var1.append("\nmaxTorqueAtLowSpeed: ");
      var1.append(this.aq);
      var1.append("\nfrontAxleIsDriving: ");
      var1.append(this.ap);
      var1.append("\nrearAxleIsDriving: ");
      var1.append(this.ao);
      var1.append("\nfrontAxleIsBraking: ");
      var1.append(this.aa);
      var1.append("\nrearAxleIsBraking: ");
      var1.append(this.an);
      var1.append("\nfrontAxleIsHandBraking: ");
      var1.append(this.am);
      var1.append("\nrearAxleIsHandBraking: ");
      var1.append(this.as);
      var1.append("\nrollingFriction: ");
      var1.append(this.ac);
      var1.append("\ndumbDownSkiddingEffectStrength: ");
      var1.append(this.at);
      var1.append("\ndesiredSkidToSteerAnglesRatio: ");
      var1.append(this.ab);
      var1.append("\nwheelFrictionConstraintStabilityTweak: ");
      var1.append(this.aw);
      var1.append("\nlowEndSteeringFullLockAngle: ");
      var1.append(this.ar);
      var1.append("\nhighEndSteeringSpeed: ");
      var1.append(this.ax);
      var1.append("\nhighEndSteeringFullLockAngle: ");
      var1.append(this.au);
      var1.append("\nsteeringChangeRate: ");
      var1.append(this.aj);
      var1.append("\nmaximumBrakingForce: ");
      var1.append(this.ak);
      var1.append("\ncentreOfMassOffset: ");
      var1.append(this.ay);
      var1.append("\ncentreOfShapeOffset: ");
      var1.append(this.ad);
      var1.append("\ncentreOfWheelsOffset: ");
      var1.append(this.ae);
      var1.append("\nmiddleWheelOffsetFromRear: ");
      var1.append(this.bd);
      var1.append("\ngraphicsPivotOffset: ");
      var1.append(this.bm);
      var1.append("\nleftWheelPretransformZangle: ");
      var1.append(this.bq);
      var1.append("\nrightWheelPretransformZangle: ");
      var1.append(this.bo);
      var1.append("\nfrontAxlePretransformXangle: ");
      var1.append(this.bl);
      var1.append("\nfrontAxlePretransformYangle: ");
      var1.append(this.bw);
      var1.append("\nrearAxlePretransformXangle: ");
      var1.append(this.bj);
      var1.append("\nrearAxlePretransformYangle: ");
      var1.append(this.bk);
      var1.append("\nsteeringScale: ");
      var1.append(this.bh);
      var1.append("\nforkLeanAngle: ");
      var1.append(this.bp);
      var1.append("\nmassScaleForContactResolution: ");
      var1.append(this.bx);
      var1.append("\ninertiaScaleForContactResolution: ");
      var1.append(this.by);
      var1.append("\nmaxLinearVelocity: ");
      var1.append(this.br);
      var1.append("\nmaxAngularVelocity: ");
      var1.append(this.bv);
      var1.append("\nbikeLeanAmount: ");
      var1.append(this.bf);
      var1.append("\nlocalAngularDampings: ");
      var1.append(this.bn);
      var1.append("\norientationCorrectionLimits: ");
      var1.append(this.bi);
      var1.append("\norientationCorrectionLimits_hard: ");
      var1.append(this.bt);
      var1.append("\nblendSpeedToVertical_01: ");
      var1.append(this.bz);
      var1.append("\nblendSpeedToSurface_01: ");
      var1.append(this.bc);
      var1.append("\nlocalAdditionalLAngularDampingsOutsideLimits: ");
      var1.append(this.bg);
      var1.append("\nlocalAdditionalLAngularDampingsOutsideLimits_hard: ");
      var1.append(this.bu);
      var1.append("\norientationCorrectionStrengths: ");
      var1.append(this.bb);
      var1.append("\norientationCorrectionStrengths_hard: ");
      var1.append(this.ba);
      var1.append("\noextraAngularPitchVelocityOnTransformation: ");
      var1.append(this.be);
      var1.append("--------\n");
      return var1.toString();
   }

   public B45() {
      this.g = 4;
      this.d = 10.0F;
      this.q = 1.3F;
      this.j = 1.3F;
      this.h = 0.6F;
      this.s = 30.0F;
      this.b = 100.0F;
      this.e = 600000.0F;
      this.l = 5.0F;
      this.w = 3.0F;
      this.r = 1.0F;
      this.v = 3.0F;
      this.y = 2.0F;
      this.p = 1.0F;
      this.x = 0.5F;
      this.u = 0.4F;
      this.z = 0.1F;
      this.t = 0.0F;
      this.m = 0.2F;
      this.n = 0.1F;
      this.k = 0.0F;
      this.i = 0.2F;
      this.o = 0.1F;
      this.a = 0.8F;
      this.f = -0.3F;
      this.c = 1.5F;
      this.az = 40.0F;
      this.ah = 10.0F;
      this.ag = 750000.0F;
      this.ai.clear();
      this.al.clear();
      this.af.clear();
      this.av.clear();
      this.aq = 1.0F;
      this.ap = true;
      this.ao = true;
      this.aa = true;
      this.an = true;
      this.am = true;
      this.as = true;
      this.ac = 0.0F;
      this.at = 0.5F;
      this.ab = 1.5F;
      this.aw = 1.0F;
      this.ar = 0.6F;
      this.ax = 25.0F;
      this.au = 0.3F;
      this.aj = 1.0F;
      this.ak = 1.0F;
      this.ay = Vector3.g;
      this.ad = Vector3.g;
      this.ae = Vector3.g;
      this.bd = 0.0F;
      this.bm = Vector3.g;
      this.bq = -4.712389F;
      this.bo = -1.5707964F;
      this.bl = -1.5707964F;
      this.bw = -3.1415927F;
      this.bj = -0.7853982F;
      this.bk = 0.0F;
      this.bh = 1.0F;
      this.bp = 0.0F;
      this.bx = 1.0F;
      this.by = 1.0F;
      this.br = 1.0E10F;
      this.bv = 1.0E10F;
      this.bf = Float.NaN;
      this.bn = Vector3.g;
      this.bb = Vector3.g;
      this.ba = Vector3.g;
      this.bi = Vector3.g;
      this.bt = Vector3.g;
      this.bz = 0.2F;
      this.bc = 0.9F;
      this.bg = Vector3.g;
      this.bu = Vector3.g;
      this.be = 0.0F;
   }
}
