package tfu;

public enum Eu326 {
   IGNORELIST_DEL(-1),
   WORLDLIST_FETCH(4),
   STATEEVENT_EVENTSBUFFER(-2),
   GENERIC_BROADCAST_EVENT(-2),
   MESSAGE_PUBLIC(-1),
   MESSAGE_PRIVATE(-2),
   RESUME_P_HSLDIALOG(2),
   FRIENDLIST_ADD(-1),
   CLIENT_CHEAT(-1),
   SEND_EMAIL_VALIDATION_CODE(-1),
   BETA_CODE_REQUEST(-1),
   SCRIPT_MESSAGE(-2),
   SEND_PING_REPLY(8),
   FRIENDLIST_DEL(-1),
   PHYSICSCONTROLDEBUGGER_STATE(-2),
   CHANGE_EMAIL_ADDRESS(-2),
   GENERIC_BROADCAST_STATE(-2),
   PING_STATISTICS(2),
   PLAYER_LOGIN(0),
   CHAT_SETMODE(1),
   WINDOW_STATUS(6),
   SET_CHATFILTERSETTINGS(3),
   EVENT_KEYBOARD(-1),
   EVENT_APPLET_FOCUS(1),
   IGNORELIST_ADD(-1),
   NO_TIMEOUT(0),
   EVENT_CAMERA_POSITION(20),
   MAP_BUILD_COMPLETE(0),
   EVENT_MOUSE_MOVE(-1),
   RESUME_P_CLANFORUMQFCDIALOG(-1),
   REFLECTION_CHECK_REPLY(-1),
   CLAN_KICKUSER(-1),
   RESUME_P_STRINGDIALOG(-1),
   SEND_SNAPSHOT(-1),
   FACE_SQUARE(4),
   EVENT_MOUSE_CLICK(6),
   CLOSE_MODAL(0),
   DETECT_MODIFIED_CLIENT(4),
   CLAN_JOINCHAT_LEAVECHAT(-1),
   TRANSMITVAR_VERIFYID(4),
   RESUME_P_COUNTDIALOG(4),
   RESUME_PAUSEBUTTON(6),
   URL_REQUEST(-1),
   RESUME_P_NAMEDIALOG(-1),
   RESUME_P_OBJDIALOG(2);

   public final int ax;

   private Eu326(int var3) {
      this.ax = var3;
   }
}
