// 
// Decompiled by Procyon v0.5.36
// 

package tfu;

public enum Eu326
{
    IGNORELIST_DEL("IGNORELIST_DEL", 23, -1), 
    WORLDLIST_FETCH("WORLDLIST_FETCH", 36, 4), 
    STATEEVENT_EVENTSBUFFER("STATEEVENT_EVENTSBUFFER", 42, -2), 
    GENERIC_BROADCAST_EVENT("GENERIC_BROADCAST_EVENT", 40, -2), 
    MESSAGE_PUBLIC("MESSAGE_PUBLIC", 30, -1), 
    MESSAGE_PRIVATE("MESSAGE_PRIVATE", 26, -2), 
    RESUME_P_HSLDIALOG("RESUME_P_HSLDIALOG", 33, 2), 
    FRIENDLIST_ADD("FRIENDLIST_ADD", 28, -1), 
    CLIENT_CHEAT("CLIENT_CHEAT", 29, -1), 
    SEND_EMAIL_VALIDATION_CODE("SEND_EMAIL_VALIDATION_CODE", 38, -1), 
    BETA_CODE_REQUEST("BETA_CODE_REQUEST", 37, -1), 
    SCRIPT_MESSAGE("SCRIPT_MESSAGE", 35, -2), 
    SEND_PING_REPLY("SEND_PING_REPLY", 34, 8), 
    FRIENDLIST_DEL("FRIENDLIST_DEL", 27, -1), 
    PHYSICSCONTROLDEBUGGER_STATE("PHYSICSCONTROLDEBUGGER_STATE", 44, -2), 
    CHANGE_EMAIL_ADDRESS("CHANGE_EMAIL_ADDRESS", 39, -2), 
    GENERIC_BROADCAST_STATE("GENERIC_BROADCAST_STATE", 41, -2), 
    PING_STATISTICS("PING_STATISTICS", 31, 2), 
    PLAYER_LOGIN("PLAYER_LOGIN", 43, 0), 
    CHAT_SETMODE("CHAT_SETMODE", 32, 1), 
    WINDOW_STATUS("WINDOW_STATUS", 7, 6), 
    SET_CHATFILTERSETTINGS("SET_CHATFILTERSETTINGS", 25, 3), 
    EVENT_KEYBOARD("EVENT_KEYBOARD", 1, -1), 
    EVENT_APPLET_FOCUS("EVENT_APPLET_FOCUS", 4, 1), 
    IGNORELIST_ADD("IGNORELIST_ADD", 24, -1), 
    NO_TIMEOUT("NO_TIMEOUT", 0, 0), 
    EVENT_CAMERA_POSITION("EVENT_CAMERA_POSITION", 5, 20), 
    MAP_BUILD_COMPLETE("MAP_BUILD_COMPLETE", 21, 0), 
    EVENT_MOUSE_MOVE("EVENT_MOUSE_MOVE", 3, -1), 
    RESUME_P_CLANFORUMQFCDIALOG("RESUME_P_CLANFORUMQFCDIALOG", 20, -1), 
    REFLECTION_CHECK_REPLY("REFLECTION_CHECK_REPLY", 8, -1), 
    CLAN_KICKUSER("CLAN_KICKUSER", 18, -1), 
    RESUME_P_STRINGDIALOG("RESUME_P_STRINGDIALOG", 19, -1), 
    SEND_SNAPSHOT("SEND_SNAPSHOT", 22, -1), 
    FACE_SQUARE("FACE_SQUARE", 13, 4), 
    EVENT_MOUSE_CLICK("EVENT_MOUSE_CLICK", 2, 6), 
    CLOSE_MODAL("CLOSE_MODAL", 10, 0), 
    DETECT_MODIFIED_CLIENT("DETECT_MODIFIED_CLIENT", 6, 4), 
    CLAN_JOINCHAT_LEAVECHAT("CLAN_JOINCHAT_LEAVECHAT", 17, -1), 
    TRANSMITVAR_VERIFYID("TRANSMITVAR_VERIFYID", 15, 4), 
    RESUME_P_COUNTDIALOG("RESUME_P_COUNTDIALOG", 11, 4), 
    RESUME_PAUSEBUTTON("RESUME_PAUSEBUTTON", 9, 6), 
    URL_REQUEST("URL_REQUEST", 14, -1), 
    RESUME_P_NAMEDIALOG("RESUME_P_NAMEDIALOG", 12, -1), 
    RESUME_P_OBJDIALOG("RESUME_P_OBJDIALOG", 16, 2);
    
    public final int ax;
    
    private Eu326(final String name, final int ordinal, final int ax) {
        this.ax = ax;
    }
}
