package tfu;

public enum Ey446 {
   LOC_PREFETCH,
   LOC_CHANGE,
   LOC_ANIM,
   LOC_ADD,
   SOUND_AREA,
   LOC_CUSTOMISE,
   FMOD_PLAY_SOUND_AREA,
   LOC_DEL,
   TEXT_COORD,
   SOUND_VORBIS_AREA,
   FMOD_SET_SOUND_PARAMETER;
}
