package tfu;

final class Ge473 {
   public static int[] ap;
   int a;
   boolean[] aa = new boolean[256];
   byte[] ab = new byte[18002];
   int[] ac = new int[16];
   int[] af = new int[256];
   int ag;
   int[] ah = new int[257];
   int ai;
   int[] aj = new int[6];
   int ak;
   int al;
   byte[] am = new byte[256];
   boolean[] an = new boolean[16];
   int ao;
   int aq;
   int[][] ar = new int[6][258];
   byte[] as = new byte[4096];
   byte[] at = new byte[18002];
   int[][] au = new int[6][258];
   int av;
   byte[][] aw = new byte[6][258];
   int[][] ax = new int[6][258];
   int[] az = new int[257];
   final int b = 50;
   int c;
   final int d = 16;
   final int e = 0;
   int f;
   final int g = 4096;
   final int h = 1;
   int i;
   final int j = 23;
   byte k;
   final int l = 4;
   int m;
   int n;
   boolean o;
   int p;
   final int q = 258;
   byte[] r;
   final int s = 6;
   int t;
   byte[] u;
   int v = 0;
   final int w = 18002;
   int x;
   int y;
   int z = 0;
}
