// 
// Decompiled by Procyon v0.5.36
// 

package tfu;

public enum Lb33
{
    zAudioRender("zAudioRender", 23), 
    SyncIncoming("SyncIncoming", 36), 
    SendScriptMessages("SendScriptMessages", 42), 
    WorldProcess("WorldProcess", 40), 
    SendState("SendState", 50), 
    P2Pservice("P2Pservice", 51), 
    MapBuild("MapBuild", 30), 
    zNavPower("zNavPower", 26), 
    GameLoop("GameLoop", 33), 
    zGraphicsSync("zGraphicsSync", 28), 
    Main_dorespawn("Main_dorespawn", 47), 
    MainDoLogouts("MainDoLogouts", 48), 
    MainLoad("MainLoad", 29), 
    ReflectionReceiver("ReflectionReceiver", 38), 
    SyncOutgoing("SyncOutgoing", 37), 
    UDP("UDP", 35), 
    TCPin("TCPin", 34), 
    zNativeRender("zNativeRender", 27), 
    NotLoggedInLoop("NotLoggedInLoop", 44), 
    DebugDialog("DebugDialog", 39), 
    VariableSystem("VariableSystem", 41), 
    MainTCPIn("MainTCPIn", 46), 
    BuildXMap_XElement_trigger("BuildXMap_XElement_trigger", 31), 
    Login("Login", 43), 
    ProcessActiveLogin("ProcessActiveLogin", 45), 
    XAreaInstanceBuild("XAreaInstanceBuild", 49), 
    Sound("Sound", 32), 
    NetClient("NetClient", 7), 
    ServiceStateChannel("ServiceStateChannel", 71), 
    Autosave("Autosave", 70), 
    ReflectionTest("ReflectionTest", 75), 
    Idle("Idle", 52), 
    Friends("Friends", 76), 
    ProcessPlayers("ProcessPlayers", 66), 
    LoginQueue("LoginQueue", 68), 
    PerNPC("PerNPC", 60), 
    AsyncJobQueue("AsyncJobQueue", 72), 
    SendScheduledMovement("SendScheduledMovement", 58), 
    ProcessNPCs("ProcessNPCs", 59), 
    NewPlayerConnections("NewPlayerConnections", 56), 
    IncomingP2P("IncomingP2P", 53), 
    SendDynamicStateCounts("SendDynamicStateCounts", 67), 
    Misc("Misc", 55), 
    NPCRunBehavior("NPCRunBehavior", 61), 
    AutoAdmin("AutoAdmin", 54), 
    NPC_XElement_trigger("NPC_XElement_trigger", 64), 
    GameNote("GameNote", 77), 
    ProcessPhysics("ProcessPhysics", 73), 
    ProcessBots("ProcessBots", 69), 
    ProcessBroadcasts("ProcessBroadcasts", 65), 
    TCP("TCP", 57), 
    NPCPathFinding("NPCPathFinding", 62), 
    NavPowerRenders("NavPowerRenders", 63), 
    AreaUpdate("AreaUpdate", 74), 
    zGamedrawmain("zGamedrawmain", 25), 
    CheckUID("CheckUID", 84), 
    NPCs("NPCs", 88), 
    NavPowerDebug("NavPowerDebug", 92), 
    RoundTripProfiling("RoundTripProfiling", 81), 
    Logout("Logout", 83), 
    GuestClanSettingsFull("GuestClanSettingsFull", 103), 
    SendNpcGone("SendNpcGone", 90), 
    TransmitVar("TransmitVar", 97), 
    VarClanDisable("VarClanDisable", 96), 
    Build("Build", 86), 
    Respawn("Respawn", 82), 
    Players("Players", 87), 
    SendNpcAppeared("SendNpcAppeared", 89), 
    FriendChatChannelList("FriendChatChannelList", 101), 
    VarClan("VarClan", 95), 
    MicroTransactions("MicroTransactions", 80), 
    ChatMessage("ChatMessage", 79), 
    RebootTimer("RebootTimer", 98), 
    GuestChatChannelFull("GuestChatChannelFull", 102), 
    SendNpcHardcoded("SendNpcHardcoded", 91), 
    AffinedClanChannelFull("AffinedClanChannelFull", 99), 
    FullVarp("FullVarp", 85), 
    Clan("Clan", 78), 
    Zones("Zones", 93), 
    Inv("Inv", 94), 
    AffinedClanSettingsFull("AffinedClanSettingsFull", 100), 
    UpdateGameplayStates("UpdateGameplayStates", 1), 
    GameEntityConstructAppend("GameEntityConstructAppend", 123), 
    DetectBroadcasterMovement("DetectBroadcasterMovement", 126), 
    NewGameEntityBody("NewGameEntityBody", 116), 
    DetectReceiverMovement("DetectReceiverMovement", 127), 
    SendOutgoing("SendOutgoing", 109), 
    ReceivePackets("ReceivePackets", 107), 
    ProcessPendingBroadcasts("ProcessPendingBroadcasts", 129), 
    ResourceCallbacks("ResourceCallbacks", 110), 
    GameEntityConstructBuilder("GameEntityConstructBuilder", 122), 
    EntitesByIdPut("EntitesByIdPut", 119), 
    GameEntityConstructStack("GameEntityConstructStack", 121), 
    NewGameEntity("NewGameEntity", 115), 
    EntitesByIdRemove("EntitesByIdRemove", 118), 
    SendFriendsState("SendFriendsState", 104), 
    ProcessIncoming("ProcessIncoming", 108), 
    Flush("Flush", 105), 
    FactionWarCounterNodeUpdate("FactionWarCounterNodeUpdate", 112), 
    GetAllBroadcastersAndReceivers("GetAllBroadcastersAndReceivers", 125), 
    UpdateEntitesById("UpdateEntitesById", 117), 
    AddCommonEventHandlers("AddCommonEventHandlers", 120), 
    FlushControls("FlushControls", 114), 
    ClearMasks("ClearMasks", 106), 
    NPC_runBehaviour("NPC_runBehaviour", 111), 
    GameEntityConstructPut("GameEntityConstructPut", 124), 
    ProcessQueuedBroadcastRecalculates("ProcessQueuedBroadcastRecalculates", 128), 
    CreateAreaInstance("CreateAreaInstance", 113), 
    Physics("Physics", 4), 
    DetectReceiverChanges("DetectReceiverChanges", 147), 
    LuaConsole("LuaConsole", 140), 
    IdProcessGcLater("IdProcessGcLater", 136), 
    GetVisibility("GetVisibility", 151), 
    DebugConsole("DebugConsole", 141), 
    IdsInUseCheck("IdsInUseCheck", 138), 
    IdProcessGcInitial("IdProcessGcInitial", 132), 
    IdShuffle("IdShuffle", 137), 
    IdAttemptAll("IdAttemptAll", 133), 
    RecalculateReceiverLoop("RecalculateReceiverLoop", 149), 
    IdLastMinuteCheck("IdLastMinuteCheck", 139), 
    CompareVisibility("CompareVisibility", 152), 
    IdAttemptOne("IdAttemptOne", 134), 
    ReceiveAppeared("ReceiveAppeared", 155), 
    DetectOneReceiverMovement("DetectOneReceiverMovement", 143), 
    LoadHeightmaps("LoadHeightmaps", 142), 
    ReceiveState("ReceiveState", 153), 
    ClearPendingBroadcasts("ClearPendingBroadcasts", 130), 
    IdSystemGc("IdSystemGc", 135), 
    UpdateBorderSets("UpdateBorderSets", 144), 
    RemoveNotBiggerSet("RemoveNotBiggerSet", 145), 
    RecalculateReceiverSetup("RecalculateReceiverSetup", 148), 
    ReceiveEvent("ReceiveEvent", 154), 
    RecalculateReceiverBody("RecalculateReceiverBody", 150), 
    AddFromBiggerSet("AddFromBiggerSet", 146), 
    GameEntityIdAllocate("GameEntityIdAllocate", 131), 
    zTweening("zTweening", 24), 
    CheckReceiveAppeared("CheckReceiveAppeared", 157), 
    GraphicsResourceFactory("GraphicsResourceFactory", 172), 
    GeoEntReceiveGone("GeoEntReceiveGone", 171), 
    RecalculateVisibilityNow("RecalculateVisibilityNow", 161), 
    InitFromCanvas("InitFromCanvas", 180), 
    CreateGroundCover("CreateGroundCover", 181), 
    RegisterSharedJs5("RegisterSharedJs5", 175), 
    TransferFullState("TransferFullState", 158), 
    WrangleAppearedServer("WrangleAppearedServer", 162), 
    InitNative("InitNative", 174), 
    ContructToolkitLoading("ContructToolkitLoading", 173), 
    CheckReceiveGone("CheckReceiveGone", 160), 
    WrangleAppearedClient("WrangleAppearedClient", 163), 
    WrangleGoneServer("WrangleGoneServer", 164), 
    TransferMessage("TransferMessage", 159), 
    EntityTriggerEventHash("EntityTriggerEventHash", 166), 
    GeoEntReceiveAppeared("GeoEntReceiveAppeared", 170), 
    InitGraphicsJava("InitGraphicsJava", 178), 
    WrangleGoneClient("WrangleGoneClient", 165), 
    CreateScriptManager("CreateScriptManager", 177), 
    AutoForwardState("AutoForwardState", 168), 
    ReceiveGone("ReceiveGone", 156), 
    InitNativeResourceLoader("InitNativeResourceLoader", 176), 
    GetDefaultCamera("GetDefaultCamera", 179), 
    AutoForwardEvent("AutoForwardEvent", 169), 
    EntityTriggerEventName("EntityTriggerEventName", 167), 
    MainRedraw("MainRedraw", 0), 
    FmodFile("FmodFile", 189), 
    FmodEvent("FmodEvent", 190), 
    Fmod_initAndPlay("Fmod_initAndPlay", 192), 
    Audio("Audio", 188), 
    Fmod_getEvent("Fmod_getEvent", 191), 
    JS5Open("JS5Open", 185), 
    FmodDownload("FmodDownload", 198), 
    ReleaseResources("ReleaseResources", 187), 
    FmodEventSystem("FmodEventSystem", 197), 
    MainThreadExecutor("MainThreadExecutor", 186), 
    AddBaseMediaPath("AddBaseMediaPath", 183), 
    InitDrawHelper("InitDrawHelper", 182), 
    AudioLoc("AudioLoc", 194), 
    EngineAudio("EngineAudio", 195), 
    MusicManager("MusicManager", 193), 
    AddBaseShaderPath("AddBaseShaderPath", 184), 
    UpdateFModCamera("UpdateFModCamera", 196), 
    MainLoop("MainLoop", 5), 
    zMainLoopBeginning("zMainLoopBeginning", 21), 
    ProcessScript("ProcessScript", 3), 
    zEvents("zEvents", 20), 
    Js5Archive("Js5Archive", 8), 
    zSoundManager("zSoundManager", 18), 
    zDebug("zDebug", 19), 
    Loading("Loading", 22), 
    ThreadEvents("ThreadEvents", 13), 
    GameDraw("GameDraw", 2), 
    Video("Video", 10), 
    NetStats("NetStats", 6), 
    Js5NativeInterface("Js5NativeInterface", 17), 
    XElementLibraryQueue("XElementLibraryQueue", 15), 
    LuaNative("LuaNative", 11), 
    ServiceJs5Native("ServiceJs5Native", 9), 
    XElementQueue("XElementQueue", 14), 
    RemovePhantomLuaRefs("RemovePhantomLuaRefs", 12), 
    XElement_CalculatePriority("XElement_CalculatePriority", 16);
    
    private Lm295 gs;
    
    public static void d(final Lb33 lb33) {
        if (lb33.gs != null) {
            lb33.gs.d();
        }
    }
    
    private Lb33(final String name, final int ordinal) {
    }
    
    public static void g(final Lb33 lb33) {
        if (lb33.gs == null) {
            lb33.gs = Lv148.q(lb33.name());
        }
        if (lb33.gs != null) {
            lb33.gs.g();
        }
    }
}
