// 
// Decompiled by Procyon v0.5.36
// 

package tfu;

import com.jagex.core.constants.J204;

public enum Mf509 implements J204
{
    NO_REPLY_FROM_SINGLE_SIGNON("NO_REPLY_FROM_SINGLE_SIGNON", 23, 36), 
    ALREADY_IN_QUEUE("ALREADY_IN_QUEUE", 30, 43), 
    INSTANCE_INVALID("INSTANCE_INVALID", 26, 39), 
    EMAIL_NOT_VALIDATED("EMAIL_NOT_VALIDATED", 33, 47), 
    INSTANCE_FULL("INSTANCE_FULL", 28, 41), 
    IN_QUEUE("IN_QUEUE", 29, 42), 
    CONNECT_FAIL("CONNECT_FAIL", 34, 50), 
    INSTANCE_NOT_SPECIFIED("INSTANCE_NOT_SPECIFIED", 27, 40), 
    BILLING_TIMEOUT("BILLING_TIMEOUT", 31, 44), 
    NOT_AGREED_TO_NDA("NOT_AGREED_TO_NDA", 32, 45), 
    IP_LIMIT("IP_LIMIT", 7, 9), 
    NO_BETA_ACCESS("NO_BETA_ACCESS", 25, 38), 
    INVALID_USERNAME_OR_PASSWORD("INVALID_USERNAME_OR_PASSWORD", 1, 3), 
    CLIENT_OUT_OF_DATE("CLIENT_OUT_OF_DATE", 4, 6), 
    PROFILE_BEING_EDITED("PROFILE_BEING_EDITED", 24, 37), 
    OK("OK", 0, 2), 
    SERVER_FULL("SERVER_FULL", 5, 7), 
    NEGATIVE_CREDIT("NEGATIVE_CREDIT", 21, 32), 
    DUPLICATE("DUPLICATE", 3, 5), 
    DISALLOWED_BY_SCRIPT("DISALLOWED_BY_SCRIPT", 20, 29), 
    FORCE_PASSWORD_CHANGE("FORCE_PASSWORD_CHANGE", 8, 11), 
    UNKNOWN_REPLY_FROM_LOGINSERVER("UNKNOWN_REPLY_FROM_LOGINSERVER", 18, 25), 
    IP_BLOCKED("IP_BLOCKED", 19, 26), 
    INVALID_SINGLE_SIGNON("INVALID_SINGLE_SIGNON", 22, 35), 
    TOO_MANY_ATTEMPTS("TOO_MANY_ATTEMPTS", 13, 16), 
    BANNED("BANNED", 2, 4), 
    INVALID_SAVE("INVALID_SAVE", 10, 13), 
    LOGINSERVER_OFFLINE("LOGINSERVER_OFFLINE", 6, 8), 
    LOGINSERVER_LOAD_ERROR("LOGINSERVER_LOAD_ERROR", 17, 24), 
    HOP_BLOCKED("HOP_BLOCKED", 15, 21), 
    UPDATE_IN_PROGRESS("UPDATE_IN_PROGRESS", 11, 14), 
    NEED_MEMBERS_ACCOUNT("NEED_MEMBERS_ACCOUNT", 9, 12), 
    LOCKED("LOCKED", 14, 18), 
    RECONNECT_OK("RECONNECT_OK", 12, 15), 
    INVALID_LOGIN_PACKET("INVALID_LOGIN_PACKET", 16, 22);
    
    private final int ao;
    
    @Override
    public int getId() {
        return this.ao;
    }
    
    private Mf509(final String name, final int ordinal, final int ao) {
        this.ao = ao;
    }
}
