package tfu;

import com.jagex.core.constants.J204;

public enum Mf509 implements J204 {
   NO_REPLY_FROM_SINGLE_SIGNON(36),
   ALREADY_IN_QUEUE(43),
   INSTANCE_INVALID(39),
   EMAIL_NOT_VALIDATED(47),
   INSTANCE_FULL(41),
   IN_QUEUE(42),
   CONNECT_FAIL(50),
   INSTANCE_NOT_SPECIFIED(40),
   BILLING_TIMEOUT(44),
   NOT_AGREED_TO_NDA(45),
   IP_LIMIT(9),
   NO_BETA_ACCESS(38),
   INVALID_USERNAME_OR_PASSWORD(3),
   CLIENT_OUT_OF_DATE(6),
   PROFILE_BEING_EDITED(37),
   OK(2),
   SERVER_FULL(7),
   NEGATIVE_CREDIT(32),
   DUPLICATE(5),
   DISALLOWED_BY_SCRIPT(29),
   FORCE_PASSWORD_CHANGE(11),
   UNKNOWN_REPLY_FROM_LOGINSERVER(25),
   IP_BLOCKED(26),
   INVALID_SINGLE_SIGNON(35),
   TOO_MANY_ATTEMPTS(16),
   BANNED(4),
   INVALID_SAVE(13),
   LOGINSERVER_OFFLINE(8),
   LOGINSERVER_LOAD_ERROR(24),
   HOP_BLOCKED(21),
   UPDATE_IN_PROGRESS(14),
   NEED_MEMBERS_ACCOUNT(12),
   LOCKED(18),
   RECONNECT_OK(15),
   INVALID_LOGIN_PACKET(22);

   private final int ao;

   public int getId() {
      return this.ao;
   }

   private Mf509(int var3) {
      this.ao = var3;
   }
}
