package tfu;

import com.jagex.core.constants.Language;
import java.util.HashMap;
import java.util.Map;

public enum Mk163 {
   INVALID_NAME("Invalid name", "Unzulässiger Name!", "Nom incorrect", "Nome inválido"),
   UNABLE_TO_DELETE_IGNORE("Unable to delete name - system busy.", "Name konnte nicht gelöscht werden - Systemfehler.", "Impossible d'effacer le nom - système occupé.", "Não foi possível deletar o nome - sistema ocupado."),
   UNABLE_TO_SEND_MESSAGE_PASSWORD_A("You appear to be telling someone your password - please don't!", "Willst du jemandem dein Passwort verraten? Das darfst du nicht! Falls das", "Il semble que vous révéliez votre mot de passe à quelqu'un - ne faites jamais ça !", "Parece que você está revelando sua senha a alguém. Não faça isso!"),
   UNABLE_TO_SEND_MESSAGE_NOTFRIEND1("Unable to send message - player not on your friends list.", "Nachricht kann nicht geschickt werden,", "Impossible d'envoyer un message - joueur non inclus dans votre liste d'amis.", "Não foi possível enviar a mensagem. O jogador não está na sua lista de amigos."),
   UNABLE_TO_SEND_MESSAGE_QUICKCHAT2((String)null, "geschickt werden.", (String)null, (String)null),
   UNABLE_TO_SEND_MESSAGE_QUICKCHATWORLD1("This player is on a quick chat world and cannot receive your message.", "Der Spieler kann auf einer Direktchat-Welt keine Nachrichten empfangen.", "Ce joueur est sur un serveur à messagerie rapide et ne peut pas recevoir votre message.", "Este jogador não pode receber sua mensagem porque está em um mundo de papo rápido."),
   UNABLE_TO_ADD_FRIEND_SYSTEM("Unable to add friend - system busy.", "Der Freund konnte nicht hinzugefügt werden, das System ist derzeit ausgelastet.", "Impossible d'ajouter un ami - système occupé.", "Não foi possível adicionar o amigo. O sistema está ocupado."),
   NOTHING_INTERESTING_HAPPENS("Nothing interesting happens.", "Nichts Interessantes passiert.", "Il ne se passe rien d'intéressant.", "Nada de interessante acontece."),
   UNABLE_TO_ADD_IGNORE_EXISTS("Unable to add name - unknown player.", "Name konnte nicht hinzugefügt werden - Spieler unbekannt.", "Impossible d'ajouter le nom - joueur inconnu.", "Não foi possível adicionar um nome - jogador desconhecido."),
   INVALID_TELEPORT("Invalid teleport!", "Unzulässiger Teleport!", "Téléportation non valide !", "Teleporte inválido!"),
   SNAPSHOT_BUFFER_EMPTY2((String)null, "die kürzlich gesprochen oder gehandelt haben.", (String)null, (String)null),
   NAMEDIALOG_NOTFOUND("That player is offline, or has privacy mode enabled.", "Dieser Spieler ist offline oder hat den Privatsphären-Modus aktiviert.", "Ce joueur est déconnecté ou en mode privé.", "O jogador está offline ou está com o modo de privacidade ativado."),
   USE_MEMBERS_SERVER_COORD("To go here you must login to a members' server.", "Du musst auf einer Mitglieder-Welt sein, um dort hinzukommen.", "Vous devez vous connecter à un serveur d'abonnés pour aller à cet endroit.", "Para entrar aqui, acesse um servidor para membros."),
   UNABLE_TO_SEND_MESSAGE_UNAVAILABLE1("Unable to send message - player unavailable.", "Deine Nachricht konnte nicht verschickt werden,", "Impossible d'envoyer un message - joueur indisponible.", "Não foi possível enviar a mensagem. O jogador não está disponível."),
   UNABLE_TO_SEND_MESSAGE_BUSY("Unable to send message - system busy.", "Deine Nachricht konnte nicht verschickt werden, das System ist derzeit ausgelastet.", "Impossible d'envoyer un message - système occupé.", "Não foi possível enviar a mensagem. O sistema está ocupado."),
   UNABLE_TO_DELETE_FRIEND("Unable to delete friend - system busy.", "Der Freund konnte nicht entfernt werden, das System ist derzeit ausgelastet.", "Impossible de supprimer un ami - système occupé.", "Não foi possível excluir o amigo. O sistema está ocupado."),
   FRIENDLIST_FULL("Your friends list is full (200 names maximum)", "Deine Freunde-Liste ist voll, du hast das Maximum von 200 erreicht.", "Votre liste d'amis est pleine (200 noms maximum).", "Sua lista de amigos está cheia. O limite é 200."),
   I_CANT_REACH_THAT("You can't reach that.", "Da kommst du nicht hin.", "Vous ne pouvez pas l'atteindre.", "Você não consegue alcançar isso."),
   UNABLE_TO_SEND_MESSAGE_NO_DISPLAYNAME_1("Unable to send message - set your display name first by logging into the game.", "Nachricht konnte nicht gesendet werden.  Bitte richte erst deinen Charakternamen ein, ", "Impossible d'envoyer le message - enregistrez un nom de personnage en vous connectant au jeu.", "Não é possível enviar a mensagem. Defina um nome de personagem antes, fazendo login no jogo."),
   UNABLE_TO_SEND_MESSAGE_UNAVAILABLE2((String)null, "der Spieler ist momentan nicht verfügbar.", (String)null, (String)null),
   UNABLE_TO_SEND_MESSAGE_NOTFRIEND2((String)null, "Spieler nicht auf deiner Freunde-Liste.", (String)null, (String)null),
   SNAPSHOT_BUFFER_EMPTY1("For that rule you can only report players who have spoken or traded recently.", "Mit dieser Option können nur Spieler gemeldet werden,", "Cette règle n'est invocable que pour les discussions ou échanges récents.", "Para essa regra, você só pode denunciar jogadores com quem tenha falado ou negociado recentemente."),
   UNABLE_TO_ADD_FRIEND_EXISTS("Unable to add friend - unknown player.", "Spieler konnte nicht hinzugefügt werden - Spieler unbekannt.", "Impossible d'ajouter l'ami - joueur inconnu.", "Não foi possível adicionar um amigo - jogador desconhecido."),
   UNABLE_TO_SEND_MESSAGE_PASSWORD_B("If you are not, please change your password to something more obscure!", "nicht der Fall ist, ändere dein Passwort zu einem ungewöhnlicheren Begriff!", "Si ce n'est pas le cas, remplacez votre mot de passe par une formule moins évidente !", "Caso não esteja, altere sua senha para algo mais obscuro!"),
   UNABLE_TO_SEND_MESSAGE_NO_DISPLAYNAME_2((String)null, "indem du dich ins Spiel einloggst.", (String)null, (String)null),
   UNABLE_TO_SEND_MESSAGE_QUICKCHAT1("You cannot send a quick chat message to a player on this world at this time.", "Einem Spieler auf dieser Welt können derzeit keine Direktchat-Nachrichten", "Impossible d'envoyer un message rapide à un joueur de ce serveur à l'heure actuelle.", "Você não pode enviar uma mensagem de papo rápido para um jogador neste mundo neste momento."),
   UNABLE_TO_ADD_IGNORE_SYSTEM("Unable to add name - system busy.", "Der Name konnte nicht hinzugefügt werden, das System ist derzeit ausgelastet.", "Impossible d'ajouter un nom - système occupé.", "Não foi possível adicionar o nome. O sistema está ocupado."),
   SWAP_NOTE_AT_BANK("Swap this note at any bank for the equivalent item.", "Dieses Zertifikat kann in einer Bank entsprechend eingetauscht werden.", "Échangez ce reçu contre l'objet correspondant dans la banque de votre choix.", "Vá a qualquer banco para trocar esta nota pelo objeto equivalente."),
   FRIENDS_CHAT_JOIN_LOWRANK("You do not have a high enough rank to join this friends chat channel.", "Dein Rang reicht nicht aus, um diesen Freundes-Chatraum zu betreten.", "Votre rang n'est pas assez élevé pour rejoindre ce canal de discussion.", "Você não tem uma classificação alta o suficiente para participar deste bate-papo entre amigos."),
   FRIENDS_CHAT_JOIN_ROOMFULL("The channel you tried to join is currently full.", "Der von dir gewünschte Chatraum ist derzeit überfüllt.", "Le canal que vous essayez de rejoindre est plein.", "O canal que você tentou acessar está cheio no momento."),
   FRIENDS_CHAT_USER_LEFT(" left the channel.", " hat den Chatraum verlassen.", " a quitté le canal.", " deixou o canal."),
   CHAT_DISABLED("Chat disabled", "Deaktiviert", "Messagerie désactivée", "Bate-papo desativado"),
   FRIENDS_CHAT_USER_KICKED(" was kicked from the channel.", " wurde aus dem Chatraum rausgeworfen.", " a été expulsé du canal.", " foi expulso do canal."),
   FRIENDS_CHAT_JOIN_SUCCESS_A_U13("Now talking in friends chat channel of player: ", "Freundes-Chat dieses Spielers beigetreten: ", "Vous participez actuellement au canal de discussion du joueur : ", "Falando no momento no bate-papo entre amigos do jogador: "),
   FRIENDS_CHAT_JOIN_ATTACKBLOCKED("You are temporarily blocked from joining channels - please try again later!", "Du darfst derzeit keine Chaträume betreten - bitte versuch es später.", "Vous êtes temporairement exclu des canaux - veuillez réessayer ultérieurement.", "Você está temporariamente impedido de entrar em canais. Tente de novo depois!"),
   FRIENDS_CHAT_SENDING_LEAVE_REQ("Sending request to leave channel...", "Chatraum wird verlassen...", "Envoi de la demande de sortie du canal...", "Enviando solicitação para deixar o canal..."),
   FRIENDS_CHAT_JOIN_BANNED("You are temporarily banned from this friends chat channel.", "Du wurdest temporär von diesem Freundes-Chatraum gesperrt.", "Vous avez été exclu temporairement de ce canal de discussion.", "Você foi temporariamente banido deste bate-papo entre amigos."),
   FRIENDS_CHAT_NOT_IN_CHANNEL("You are not currently in a channel.", "Du befindest dich derzeit nicht in einem Chatraum.", "Vous n'êtes dans aucun canal à l'heure actuelle.", "No momento você não está em um canal."),
   FRIENDS_CHAT_ATTEMPTING_JOIN("Attempting to join channel...", "Chatraum wird betreten...", "Tentative de connexion au canal...", "Tentando acessar canal..."),
   UNABLE_TO_SEND_MESSAGE_FRIENDS_CHAT_ERROR("Error sending message to friends chat - please try again later!", "Fehler beim Versenden der Nachricht - bitte versuch es später erneut.", "Erreur lors de l'envoi de ce message – veuillez réessayer ultérieurement !", "Erro ao enviar mensagem para bate-papo entre amigos - favor tentar novamente mais tarde!"),
   UNDER13_FRIENDSCHAT_PREFIX("friends_chat", "friends_chat", "friends_chat", "friends_chat"),
   FRIENDS_CHAT_JOIN_ERROR("Error joining friends chat channel - please try again later!", "Fehler beim Betreten des Freundes-Chatraums - bitte versuch es später erneut.", "Erreur lors de la connexion au canal de discussion - veuillez réessayer ultérieurement !", "Erro ao participar do bate-papo entre-amigos - favor tentar novamente mais tarde!"),
   UNABLE_TO_SEND_MESSAGE_FRIENDS_CHAT_TOO_LOW_RANK("You are not allowed to talk in this friends chat channel.", "Du darfst in diesem Freundes-Chatraum nicht reden.", "Vous n'êtes pas autorisé à parler dans ce canal de discussion.", "Você pode falar neste bate-papo entre amigos."),
   FRIENDS_CHAT_JOIN_IN_PROGRESS("Already attempting to join a channel - please wait...", "Du versuchst bereits, einem Chatraum beizutreten - bitte warte.", "Tentative de connexion au canal déjà en cours - veuillez patienter...", "Já há uma tentativa de entrar em um canal. Aguarde..."),
   UNABLE_TO_SEND_MESSAGE_NOT_IN_FRIENDS_CHAT("You are not currently in a friends chat channel.", "Du befindest dich derzeit nicht in einem Freundes-Chatraum.", "Vous ne faites pas partie d'un canal de discussion.", "No momento, você não está no bate-papo entre amigos."),
   FRIENDS_CHAT_NOT_AVAILABLE("Unable to join friends chat at this time - please try again later!", "Freundes-Chatraum kann nicht betreten werden - bitte versuch es später erneut.", "Vous ne pouvez pas rejoindre ce canal de discussion pour le moment - veuillez réessayer ultérieurement !", "Não foi possível participar do bate-papo entre amigos - favor tentar novamente mais tarde!"),
   FRIENDS_CHAT_LEAVE_KICKED("You have been kicked from the channel.", "Du wurdest aus dem Chatraum rausgeworfen.", "Vous avez été expulsé du canal.", "Você foi expulso do canal."),
   FRIENDS_CHAT_JOIN_IGNORELIST("You are not allowed to join this user's friends chat channel.", "Du darfst den Freundes-Chatraum dieses Benutzers nicht betreten.", "Vous n'êtes pas autorisé à rejoindre le canal de discussion de cet utilisateur.", "Você não pode participar do bate-papo entre amigos deste usuário."),
   FRIENDS_CHAT_JOIN_NOTEXIST("The channel you tried to join does not exist.", "Der von dir gewünschte Chatraum existiert nicht.", "Le canal que vous essayez de rejoindre n'existe pas.", "O canal que você tentou acessar não existe."),
   FRIENDS_CHAT_JOIN_SUCCESS_A("Now talking in friends chat channel ", "Freundes-Chatraum: ", "Vous participez actuellement au canal de discussion : ", "Falando no momento no bate-papo entre amigos: "),
   FRIENDS_CHAT_STILL_IN_CHANNEL("Please wait until you are logged out of your previous channel.", "Bitte warte, bis du den vorherigen Chatraum verlassen hast.", "Veuillez attendre d'être déconnecté(e) de votre canal précédent.", "Aguarde até se desconectar do canal anterior."),
   FRIENDS_CHAT_LEAVE_IN_PROGRESS("Leave request already in progress - please wait...", "Du versuchst bereits, einen Chatraum zu verlassen - bitte warte.", "Demande de sortie déjà effectuée - veuillez patienter...", "Solicitação de saída já em andamento. Aguarde..."),
   FRIENDS_CHAT_INVALID_NAME("Invalid channel name entered!", "Ungültiger Chatraum-Name angegeben.", "Nom de canal incorrect !", "Nome de canal inválido!"),
   FRIENDS_CHAT_USER_JOINED(" joined the channel.", " hat den Chatraum betreten.", " a rejoint le canal.", " entrou no canal."),
   USE_MEMBERS_SERVER_LOCATION("To interact with this please login to a members' server.", "Logg dich auf einer Mitglieder-Welt ein, um damit zu interagieren.", "Veuillez vous connecter à un serveur d'abonnés pour cette interaction.", "Para interagir, acesse um servidor para membros."),
   FRIENDS_CHAT_KICK_USER_HIGHER("You do not have permission to kick this user.", "Du darfst diesen Benutzer nicht rauswerfen.", "Vous n'êtes pas autorisé à expulser cet utilisateur.", "Você não tem permissão para expulsar este usuário."),
   MUTED_TEMPORARY("You have been temporarily muted due to breaking a rule.", "Aufgrund eines Regelverstoßes wurdest du vorübergehend stumm geschaltet.", "La messagerie instantanée a été temporairement bloquée suite à une infraction.", "Você foi temporariamente vetado por ter violado uma regra."),
   MUTED_PREVENT("To prevent further mutes please read the rules.", "Um eine erneute Stummschaltung zu verhindern, lies bitte die Regeln.", "Pour éviter un nouveau blocage, lisez le règlement.", "Para evitar outros vetos, leia as regras."),
   FRIENDS_CHAT_ENABLED_B("Join your channel by clicking 'Join Chat' and typing: ", "Klick auf 'Betreten' und gib ein: ", "Pour rejoindre votre canal, cliquez sur « Participer » et entrez : ", "Para entrar no seu canal, clique em \"Acessar bate-papo\" e digite: "),
   FRIENDS_CHAT_KICK_LOW_RANK("You do not have permission to kick users in this channel.", "Du darfst keine Benutzer aus diesem Chatraum rauswerfen.", "Vous n'êtes pas autorisé à expulser des utilisateurs de ce canal.", "Você não tem permissão para expulsar usuários neste canal."),
   MAINLOAD120B("Loaded sprites", "Sprites geladen.", "Sprites chargés", "Sprites carregados"),
   MUTED_TEMPORARY_TIME_B(" days.", " Tage.", " jours.", " dias."),
   ATTEMPT_TO_REESTABLISH("Please wait - attempting to reestablish.", "Bitte warte - es wird versucht, die Verbindung wiederherzustellen.", "Veuillez patienter - tentative de rétablissement.", "Tentando reestabelecer conexão. Aguarde."),
   CONLOST("Connection lost.", "Verbindung abgebrochen.", "Connexion perdue.", "Conexão perdida."),
   FRIENDS_CHAT_KICK_SUCCESS("Your request to kick/ban this user was successful.", "Der Rauswurf/die Sperrung war erfolgreich.", "Votre demande d'exclusion de ce joueur a été acceptée.", "Seu pedido para expulsar/suspender este jogador foi bem sucedido."),
   FRIENDS_CHAT_DISABLED("Your friends chat channel has now been disabled!", "Dein Freundes-Chat ist jetzt ausgeschaltet.", "Votre canal de discussion est maintenant désactivé !", "O seu bate-papo entre amigos foi desativado!"),
   FRIENDS_CHAT_KICK_SUCCESS_RESET("Your request to refresh this user's temporary ban was successful.", "Die Verlängerung der temporären Sperrung dieses Spielers war erfolgreich.", "Le renouvellement d'exclusion temporaire de ce joueur a été accepté.", "Seu pedido para reiniciar a suspensão temporária deste jogador foi bem sucedido."),
   MUTED_TEMPORARY_TIME_A("This mute will remain for a further ", "Diese Stummschaltung gilt für weitere ", "Votre accès restera bloqué encore ", "Este veto permanecerá por mais "),
   MAINLOAD110B("Loaded config", "Konfig geladen.", "Fichiers config chargés", "Config carregada"),
   PROFILING("Profiling...", "Profiling...", "Profilage...", "Profiling..."),
   FRIENDS_CHAT_ENABLED_A("Your friends chat channel has now been enabled!", "Dein Freundes-Chat ist jetzt eingeschaltet.", "Votre canal de discussion est maintenant activé !", "O seu bate-papo entre amigos foi ativado!"),
   FRIENDS_CHAT_LEAVE_DEFAULT("You have left the channel.", "Du hast den Chatraum verlassen.", "Vous avez quitté le canal.", "Você saiu do canal."),
   CHECKING_FOR_UPDATES("Checking for updates - ", "Suche nach Updates - ", "Vérification des mises à jour - ", "Verificando atualizações - "),
   MAINLOAD120("Loading sprites - ", "Lade Sprites - ", "Chargement des sprites - ", "Carregando sprites - "),
   MUTED_TEMPORARY_1DAY("You will be un-muted within 24 hours.", "Du wirst innerhalb der nächsten 24 Stunden wieder sprechen können.", "Vous aurez à nouveau accès à la messagerie instantanée dans 24 heures.", "O veto será retirado dentro de 24 horas."),
   DOWNLOADING_UPDATES("Fetching Updates - ", "Lade Update - ", "Chargement des MAJ - ", "Carregando atualizações - "),
   FRIENDS_CHAT_KICK_NOT_FOUND("That user is not in this channel.", "Dieser Benutzer befindet sich nicht in diesem Chatraum.", "Cet utilisateur n'est pas dans ce canal.", "Esse usuário não está no canal."),
   FRIENDS_CHAT_LEAVE_REMOVED("You have been removed from this channel.", "Du wurdest aus dem Chatraum entfernt.", "Vous avez été supprimé de ce canal.", "Você foi retirado desse canal."),
   MUTED_PERMANENT("You have been permanently muted due to breaking a rule.", "Du wurdest permanent stumm geschaltet, da du gegen eine Regel verstoßen hast.", "L'accès à la messagerie instantanée vous a définitivement été retiré suite à une infraction.", "Você foi permanentemente vetado por ter violado uma regra."),
   LOADING("Loading - please wait.", "Ladevorgang - bitte warte.", "Chargement en cours. Veuillez patienter.", "Carregando. Aguarde."),
   MAINLOAD110("Loading config - ", "Lade Konfiguration - ", "Chargement des fichiers config - ", "Carregando config - "),
   DEBUG_CONSOLE_ERROR("There was an error executing the command.", "Es gab einen Fehler beim Ausführen des Befehls.", "Une erreur s'est produite lors de l'exécution de la commande.", "Houve um erro quando o comando foi executado."),
   UNABLETOFIND("Unable to find ", "Spieler kann nicht gefunden werden: ", "Impossible de trouver ", "Não é possível encontrar "),
   ATTACK("Attack", "Angreifen", "Attaquer", "Atacar"),
   MAINLOAD190B("Loaded client variable data", "Client-Variablen geladen", "Variables du client chargées", "As variáveis do sistema foram carregadas"),
   CHOOSEOPTION("Choose Option", "Wähl eine Option", "Choisir une option", "Selecionar opção"),
   MAINLOAD150B("Loaded interface scripts", "Interface-Skripte geladen", "Interfaces chargées", "Interfaces carregadas"),
   MAINLOAD140B("Loaded interfaces", "Benutzeroberfläche geladen.", "Interfaces chargées", "Interfaces carregadas"),
   WALKHERE("Walk here", "Hierhin gehen", "Atteindre", "Caminhar para cá"),
   MAINLOAD160("Loading additional fonts - ", "Lade Zusatzschriftarten - ", "Chargement de polices secondaires - ", "Carregando fontes principais - "),
   FRIENDLOGOUT(" has logged out.", " loggt sich aus.", " s'est déconnecté.", " saiu do jogo."),
   SNAPSHOT_PLEASECLOSE2((String)null, "bevor du die Option 'Regelverstoß melden' benutzt.", (String)null, (String)null),
   FRIENDLOGIN(" has logged in.", " loggt sich ein.", " s'est connecté.", " entrou no jogo."),
   MAINLOAD180B("Loaded world list data", "Liste der Welten geladen", "Liste des serveurs chargée", "Dados da lista de mundos carregados"),
   SNAPSHOT_PLEASECLOSE1("Please close the interface you have open before using 'Report Abuse'.", "Bitte schließ die momentan geöffnete Benutzeroberfläche,", "Fermez l'interface que vous avez ouverte avant d'utiliser le bouton « Signaler un abus ».", "Feche a interface aberta antes de usar o recurso \"Denunciar abuso\"."),
   MAINLOAD130("Loading wordpack - ", "Lade Wordpack - ", "Chargement du module texte - ", "Carregando pacote de palavras - "),
   MAINLOAD150("Loading interface scripts - ", "Lade Interface-Skripte - ", "Chargement des interfaces - ", "Carregando interfaces - "),
   MAINLOAD130B("Loaded wordpack", "Wordpack geladen.", "Module texte chargé", "Pacote de palavras carregado"),
   MAINLOAD170("Loading world map - ", "Lade Weltkarte - ", "Chargement de la mappemonde - ", "Carregando mapa-múndi - "),
   EXAMINE("Examine", "Untersuchen", "Examiner", "Examinar"),
   LOADINGDOTDOTDOT("Loading...", "Lade...", "Chargement en cours...", "Carregando..."),
   SYSTEMUPDATE("System update in: ", "System-Update in: ", "Mise à jour système dans : ", "Atualização do sistema em: "),
   MAINLOAD180("Loading world list data", "Lade Liste der Welten", "Chargement de la liste des serveurs", "Carregando dados da lista de mundos"),
   MAINLOAD140("Loading interfaces - ", "Lade Benutzeroberfläche - ", "Chargement des interfaces - ", "Carregando interfaces - "),
   MAINLOAD160B("Loaded additional fonts", "Zusatzschriftarten geladen", "Polices secondaires chargées", "Fontes principais carregadas"),
   USE("Use", "Benutzen", "Utiliser", "Usar"),
   MOREOPTIONS(" more options", " weitere Optionen", " autres options", " mais opções"),
   MAINLOAD170B("Loaded world map", "Weltkarte geladen", "Mappemonde chargée", "Mapa-múndi carregado"),
   NO_NAME_PLAYERNAME("#Player", "#Spieler", "#Joueur", "#Jogador"),
   IGNORECANTADDSELF("You can't add yourself to your own ignore list.", "Du kannst dich nicht auf deine eigene Ignorieren-Liste setzen!", "Vous ne pouvez pas ajouter votre nom à votre liste noire.", "Você não pode adicionar a si próprio à sua lista de ignorados."),
   THOUSAND_SHORT("K", "T", "K", "K"),
   MINISEPERATOR(" ", ": ", " ", " "),
   REMOVEFRIEND1("Please remove ", "Bitte entferne ", "Veuillez commencer par supprimer ", "Remova "),
   FROM("From", "Von:", "De", "De"),
   MILLION_SHORT("M", "M", "M", "M"),
   SKILL("skill: ", "Fertigkeit: ", "compétence ", "habilidade: "),
   MILLION("M", "M", "M", "M"),
   RATING("rating: ", "Kampfstufe: ", "classement ", "qualificação: "),
   REMOVEIGNORE1("Please remove ", "Bitte entferne ", "Veuillez commencer par supprimer ", "Remova "),
   THOUSAND("K", "T", "K", "K"),
   REMOVEFRIEND2(" from your friends list first.", " zuerst von deiner Freunde-Liste!", " de votre liste d'amis.", " da sua lista de amigos primeiro."),
   PLEASEWAIT("Please wait...", "Bitte warte...", "Veuillez attendre", "Aguarde..."),
   CHATCOL2("green:", "grün:", "vert:", "verde:"),
   FRIENDLISTDUPE(" is already on your friends list.", " steht bereits auf deiner Freunde-Liste!", " est déjà dans votre liste d'amis.", " já está na sua lista de amigos."),
   SELF("Self", "Mich", "Moi", "Eu"),
   CHATCOL0("yellow:", "gelb:", "jaune:", "amarelo:"),
   FACEHERE("Face here", "Hierhin drehen", "Regarder dans cette direction", "Virar para cá"),
   CLOSE("Close", "Bitte schließ die momentan geöffnete Benutzeroberfläche,", "Fermez l'interface que vous avez ouverte avant d'utiliser le bouton « Signaler un abus ».", "Feche a interface aberta antes de usar o recurso \"Denunciar abuso\"."),
   IGNORELISTFULL("Your ignore list is full. Max of 100 users.", "Deine Ignorieren-Liste ist voll, du kannst nur 100 Spieler darauf eintragen.", "Votre liste noire est pleine (100 noms maximum).", "Sua lista de ignorados está cheia. O limite é 100 usuários."),
   IGNORELISTDUPE(" is already on your ignore list.", " steht bereits auf deiner Ignorieren-Liste!", " est déjà dans votre liste noire.", " já está na sua lista de ignorados."),
   FRIENDLIST_TIMED_SAVE("Changes will take effect on your friends chat in the next 60 seconds.", "Die Änderungen am Freundes-Chat werden innerhalb von 60 Sekunden übernommen.", "Les modifications seront apportés à votre canal de discussion dans les 60 prochaines secondes.", "Mundanças vão ocorrer em seu bate-papo entre amigos nos próximos 60 segundos."),
   CHATCOL1("red:", "rot:", "rouge:", "vermelho:"),
   REMOVEIGNORE2(" from your ignore list first.", " zuerst von deiner Ignorieren-Liste!", " de votre liste noire.", " da sua lista de ignorados primeiro."),
   FRIENDCANTADDSELF("You can't add yourself to your own friends list.", "Du kannst dich nicht auf deine eigene Freunde-Liste setzen!", "Vous ne pouvez pas ajouter votre nom à votre liste d'amis.", "Você não pode adicionar a si próprio à sua lista de amigos."),
   LEVEL("level: ", "Stufe: ", "niveau ", "nível: "),
   USE_MEMBERS_SERVER_ITEM("To use this item please login to a members' server.", "Du musst auf einer Mitglieder-Welt sein, um diesen Gegenstand zu benutzen.", "Veuillez vous connecter à un serveur d'abonnés pour utiliser cet objet.", "Acesse um servidor para membros para usar este objeto."),
   CHATCOL4("purple:", "lila:", "violet:", "roxo:"),
   CHATCOL8("flash3:", "blinken3:", "clignotant3:", "brilho3:"),
   CHATCOL5("white:", "weiss:", "blanc:", "branco:"),
   CHATCOL9("glow1:", "leuchten1:", "brillant1:", "brilho1:"),
   CHATCOL7("flash2:", "blinken2:", "clignotant2:", "flash2:"),
   CHATCOL10("glow2:", "leuchten2:", "brillant2:", "brilho2:"),
   CHATCOL11("glow3:", "leuchten3:", "brillant3:", "brilho3:"),
   CHATCOL6("flash1:", "blinken1:", "clignotant1:", "flash1:"),
   CHATEFFECT2("wave2:", "welle2:", "ondulation2:", "onda2:"),
   UNKNOWN_FRIEND_DISPLAYNAME_PLACEHOLDER("Friend", "Freund", "Ami", "Amigo"),
   CHATEFFECT1("wave:", "welle:", "ondulation:", "onda:"),
   CHATEFFECT4("scroll:", "scrollen:", "déroulement:", "rolagem:"),
   CHATCOL3("cyan:", "blaugrün:", "cyan:", "cyan:"),
   CHATEFFECT5("slide:", "gleiten:", "glissement:", "deslizamento:"),
   CHATEFFECT3("shake:", "schütteln:", "tremblement:", "tremor:"),
   DEBUG_CONSOLE_INFO("This is the developer console. To close, press the `, ² or § keys on your keyboard.", "Das ist die Entwicklerkonsole. Zum Schließen, die Tasten `, ² or § drücken.", "Ceci est la console de développement. Pour la fermer, appuyez sur les touches `, ² ou §.", "Este é o painel de controle do desenvolvedor. Para fechar, pressione `, ² ou §."),
   MEMBERS_OBJECT("Members object", "Gegenstand für Mitglieder", "Objet d'abonnés", "Objeto para membros"),
   ABUSE_REPORT_RECEIVED("Thank-you, your abuse report has been received.", "Vielen Dank, deine Meldung ist bei uns eingegangen.", "Merci, nous avons bien reçu votre rapport d'abus.", "Obrigado. Sua denúncia de abuso foi recebida."),
   CANCEL("Cancel", "Abbrechen", "Annuler", "Cancelar"),
   YOU_CANNOT_REPORT_STAFF_FOR_IMPERSONATION3("You can report that person under a different rule.", "Diese Person kann bezüglich einer anderen Regel gemeldet werden.", "Vous pouvez signaler cette personne pour une autre infraction aux règles.", "Você não pode denunciar essa pessoa de acordo com uma regra diferente."),
   LENT_ITEM_RETURN("Discard", "Ablegen", "Jeter", "Descartar"),
   YOU_CANNOT_REPORT_STAFF_FOR_IMPERSONATION1("You cannot report that person for Staff Impersonation, they are Jagex Staff.", "Diese Person ist ein Jagex-Mitarbeiter!", "Cette personne est un membre du personnel de Jagex, vous ne pouvez pas la signaler pour abus d'identité.", "Você não pode denunciar essa pessoa por tentar se passar por membro da equipe Jagex, pois ela faz parte da equipe."),
   YOU_CANNOT_REPORT_STAFF_FOR_IMPERSONATION2("You can spot a Jagex moderator by the gold crown next to their name.", "Jagex-Mitarbeiter haben eine goldene Krone neben ihrem Namen.", "Vous pouvez reconnaître les modérateurs Jagex à la couronne dorée en regard de leur nom.", "Os moderadores da Jagex são identificados por uma coroa dourada próxima ao \u007fnome."),
   UNABLE_TO_SEND_SNAPSHOT_BUSY("Unable to send abuse report - system busy.", "Meldung konnte nicht gesendet werden - Systeme überlastet", "Impossible de signaler un abus - Erreur système", "Sistema ocupado. Não foi possível enviar sua denúncia de abuso."),
   SELECT("Select", "Auswählen", "Sélectionner", "Selecionar"),
   DEBUG_CONSOLE_UNKNOWNCOMMAND("Unknown developer command: ", "Unbekannter Befehl: ", "Commande inconnue : ", "Comando desconhecido: "),
   TAKE("Take", "Nehmen", "Prendre", "Pegar"),
   MEMBERS_DESC("Login to a members' server to use this object.", "Du musst auf einer Mitglieder-Welt sein, um diesen Gegenstand zu benutzen.", "Connectez-vous à un serveur d'abonnés pour utiliser cet objet.", "Acesse um servidor para membros para usar este objeto."),
   YOU_ALREADY_SENT_A_SNAPSHOT1("You have sent too many abuse reports today! Do not abuse this system!", "Du hast heute schon zu viele Regelverstöße gemeldet! Missbrauch das System nicht!", "Vous avez signalé trop d’abus pour aujourd’hui. N’abusez pas de ce système !", "Você já denunciou abuso muitas vezes hoje. Não abuse do sistema!"),
   INVALID_PLAYER_NAME("Invalid player name.", "Unzulässiger Charaktername!", "Nom de joueur incorrect.", "Nome de jogador inválido."),
   DROP("Drop", "Fallen lassen", "Poser", "Largar"),
   BOUGHT_ITEM_DISCARD("Discard", "Ablegen", "Jeter", "Descartar"),
   CONTINU("Continue", "Weiter", "Continuer", "Continuar"),
   OK("Ok", "Okay", "OK", "Ok"),
   YOU_CANT_REPORT_YOURSELF("You can't report yourself!", "Du kannst dich nicht selbst melden!", "Vous ne pouvez pas vous signaler vous-même !", "Você não pode denunciar a si próprio!");

   private final Map fc = new HashMap(7);

   public static String g(Mk163 var0, Language var1) {
      return (String)var0.fc.get(var1);
   }

   private Mk163(String var3, String var4, String var5, String var6) {
      this.fc.put(Language.EN, var3);
      this.fc.put(Language.DE, var4);
      this.fc.put(Language.FR, var5);
      this.fc.put(Language.PT, var6);
   }
}
