/*
 * Decompiled with CFR 0.146.
 */
package tfu;

import com.jagex.core.constants.Language;
import java.util.HashMap;
import java.util.Map;

public enum Mk163 {
    DEBUG_CONSOLE_INFO("This is the developer console. To close, press the `, \u00b2 or \u00a7 keys on your keyboard.", "Das ist die Entwicklerkonsole. Zum Schlie\u00dfen, die Tasten `, \u00b2 or \u00a7 dr\u00fccken.", "Ceci est la console de d\u00e9veloppement. Pour la fermer, appuyez sur les touches `, \u00b2 ou \u00a7.", "Este \u00e9 o painel de controle do desenvolvedor. Para fechar, pressione `, \u00b2 ou \u00a7."),
    DEBUG_CONSOLE_ERROR("There was an error executing the command.", "Es gab einen Fehler beim Ausf\u00fchren des Befehls.", "Une erreur s'est produite lors de l'ex\u00e9cution de la commande.", "Houve um erro quando o comando foi executado."),
    DEBUG_CONSOLE_UNKNOWNCOMMAND("Unknown developer command: ", "Unbekannter Befehl: ", "Commande inconnue : ", "Comando desconhecido: "),
    CANCEL("Cancel", "Abbrechen", "Annuler", "Cancelar"),
    NO_NAME_PLAYERNAME("#Player", "#Spieler", "#Joueur", "#Jogador"),
    MEMBERS_OBJECT("Members object", "Gegenstand f\u00fcr Mitglieder", "Objet d'abonn\u00e9s", "Objeto para membros"),
    MEMBERS_DESC("Login to a members' server to use this object.", "Du musst auf einer Mitglieder-Welt sein, um diesen Gegenstand zu benutzen.", "Connectez-vous \u00e0 un serveur d'abonn\u00e9s pour utiliser cet objet.", "Acesse um servidor para membros para usar este objeto."),
    SWAP_NOTE_AT_BANK("Swap this note at any bank for the equivalent item.", "Dieses Zertifikat kann in einer Bank entsprechend eingetauscht werden.", "\u00c9changez ce re\u00e7u contre l'objet correspondant dans la banque de votre choix.", "V\u00e1 a qualquer banco para trocar esta nota pelo objeto equivalente."),
    LENT_ITEM_RETURN("Discard", "Ablegen", "Jeter", "Descartar"),
    BOUGHT_ITEM_DISCARD("Discard", "Ablegen", "Jeter", "Descartar"),
    TAKE("Take", "Nehmen", "Prendre", "Pegar"),
    DROP("Drop", "Fallen lassen", "Poser", "Largar"),
    OK("Ok", "Okay", "OK", "Ok"),
    SELECT("Select", "Ausw\u00e4hlen", "S\u00e9lectionner", "Selecionar"),
    CONTINU("Continue", "Weiter", "Continuer", "Continuar"),
    INVALID_PLAYER_NAME("Invalid player name.", "Unzul\u00e4ssiger Charaktername!", "Nom de joueur incorrect.", "Nome de jogador inv\u00e1lido."),
    YOU_CANT_REPORT_YOURSELF("You can't report yourself!", "Du kannst dich nicht selbst melden!", "Vous ne pouvez pas vous signaler vous-m\u00eame !", "Voc\u00ea n\u00e3o pode denunciar a si pr\u00f3prio!"),
    YOU_ALREADY_SENT_A_SNAPSHOT1("You have sent too many abuse reports today! Do not abuse this system!", "Du hast heute schon zu viele Regelverst\u00f6\u00dfe gemeldet! Missbrauch das System nicht!", "Vous avez signal\u00e9 trop d\u2019abus pour aujourd\u2019hui. N\u2019abusez pas de ce syst\u00e8me !", "Voc\u00ea j\u00e1 denunciou abuso muitas vezes hoje. N\u00e3o abuse do sistema!"),
    YOU_CANNOT_REPORT_STAFF_FOR_IMPERSONATION1("You cannot report that person for Staff Impersonation, they are Jagex Staff.", "Diese Person ist ein Jagex-Mitarbeiter!", "Cette personne est un membre du personnel de Jagex, vous ne pouvez pas la signaler pour abus d'identit\u00e9.", "Voc\u00ea n\u00e3o pode denunciar essa pessoa por tentar se passar por membro da equipe Jagex, pois ela faz parte da equipe."),
    YOU_CANNOT_REPORT_STAFF_FOR_IMPERSONATION2("You can spot a Jagex moderator by the gold crown next to their name.", "Jagex-Mitarbeiter haben eine goldene Krone neben ihrem Namen.", "Vous pouvez reconna\u00eetre les mod\u00e9rateurs Jagex \u00e0 la couronne dor\u00e9e en regard de leur nom.", "Os moderadores da Jagex s\u00e3o identificados por uma coroa dourada pr\u00f3xima ao \u007fnome."),
    YOU_CANNOT_REPORT_STAFF_FOR_IMPERSONATION3("You can report that person under a different rule.", "Diese Person kann bez\u00fcglich einer anderen Regel gemeldet werden.", "Vous pouvez signaler cette personne pour une autre infraction aux r\u00e8gles.", "Voc\u00ea n\u00e3o pode denunciar essa pessoa de acordo com uma regra diferente."),
    ABUSE_REPORT_RECEIVED("Thank-you, your abuse report has been received.", "Vielen Dank, deine Meldung ist bei uns eingegangen.", "Merci, nous avons bien re\u00e7u votre rapport d'abus.", "Obrigado. Sua den\u00fancia de abuso foi recebida."),
    UNABLE_TO_SEND_SNAPSHOT_BUSY("Unable to send abuse report - system busy.", "Meldung konnte nicht gesendet werden - Systeme \u00fcberlastet", "Impossible de signaler un abus - Erreur syst\u00e8me", "Sistema ocupado. N\u00e3o foi poss\u00edvel enviar sua den\u00fancia de abuso."),
    INVALID_NAME("Invalid name", "Unzul\u00e4ssiger Name!", "Nom incorrect", "Nome inv\u00e1lido"),
    USE_MEMBERS_SERVER_ITEM("To use this item please login to a members' server.", "Du musst auf einer Mitglieder-Welt sein, um diesen Gegenstand zu benutzen.", "Veuillez vous connecter \u00e0 un serveur d'abonn\u00e9s pour utiliser cet objet.", "Acesse um servidor para membros para usar este objeto."),
    USE_MEMBERS_SERVER_LOCATION("To interact with this please login to a members' server.", "Logg dich auf einer Mitglieder-Welt ein, um damit zu interagieren.", "Veuillez vous connecter \u00e0 un serveur d'abonn\u00e9s pour cette interaction.", "Para interagir, acesse um servidor para membros."),
    NOTHING_INTERESTING_HAPPENS("Nothing interesting happens.", "Nichts Interessantes passiert.", "Il ne se passe rien d'int\u00e9ressant.", "Nada de interessante acontece."),
    I_CANT_REACH_THAT("You can't reach that.", "Da kommst du nicht hin.", "Vous ne pouvez pas l'atteindre.", "Voc\u00ea n\u00e3o consegue alcan\u00e7ar isso."),
    INVALID_TELEPORT("Invalid teleport!", "Unzul\u00e4ssiger Teleport!", "T\u00e9l\u00e9portation non valide !", "Teleporte inv\u00e1lido!"),
    USE_MEMBERS_SERVER_COORD("To go here you must login to a members' server.", "Du musst auf einer Mitglieder-Welt sein, um dort hinzukommen.", "Vous devez vous connecter \u00e0 un serveur d'abonn\u00e9s pour aller \u00e0 cet endroit.", "Para entrar aqui, acesse um servidor para membros."),
    UNABLE_TO_ADD_FRIEND_SYSTEM("Unable to add friend - system busy.", "Der Freund konnte nicht hinzugef\u00fcgt werden, das System ist derzeit ausgelastet.", "Impossible d'ajouter un ami - syst\u00e8me occup\u00e9.", "N\u00e3o foi poss\u00edvel adicionar o amigo. O sistema est\u00e1 ocupado."),
    UNABLE_TO_ADD_FRIEND_EXISTS("Unable to add friend - unknown player.", "Spieler konnte nicht hinzugef\u00fcgt werden - Spieler unbekannt.", "Impossible d'ajouter l'ami - joueur inconnu.", "N\u00e3o foi poss\u00edvel adicionar um amigo - jogador desconhecido."),
    UNABLE_TO_ADD_IGNORE_SYSTEM("Unable to add name - system busy.", "Der Name konnte nicht hinzugef\u00fcgt werden, das System ist derzeit ausgelastet.", "Impossible d'ajouter un nom - syst\u00e8me occup\u00e9.", "N\u00e3o foi poss\u00edvel adicionar o nome. O sistema est\u00e1 ocupado."),
    UNABLE_TO_ADD_IGNORE_EXISTS("Unable to add name - unknown player.", "Name konnte nicht hinzugef\u00fcgt werden - Spieler unbekannt.", "Impossible d'ajouter le nom - joueur inconnu.", "N\u00e3o foi poss\u00edvel adicionar um nome - jogador desconhecido."),
    FRIENDLIST_FULL("Your friends list is full (200 names maximum)", "Deine Freunde-Liste ist voll, du hast das Maximum von 200 erreicht.", "Votre liste d'amis est pleine (200 noms maximum).", "Sua lista de amigos est\u00e1 cheia. O limite \u00e9 200."),
    UNABLE_TO_DELETE_FRIEND("Unable to delete friend - system busy.", "Der Freund konnte nicht entfernt werden, das System ist derzeit ausgelastet.", "Impossible de supprimer un ami - syst\u00e8me occup\u00e9.", "N\u00e3o foi poss\u00edvel excluir o amigo. O sistema est\u00e1 ocupado."),
    UNABLE_TO_DELETE_IGNORE("Unable to delete name - system busy.", "Name konnte nicht gel\u00f6scht werden - Systemfehler.", "Impossible d'effacer le nom - syst\u00e8me occup\u00e9.", "N\u00e3o foi poss\u00edvel deletar o nome - sistema ocupado."),
    UNABLE_TO_SEND_MESSAGE_BUSY("Unable to send message - system busy.", "Deine Nachricht konnte nicht verschickt werden, das System ist derzeit ausgelastet.", "Impossible d'envoyer un message - syst\u00e8me occup\u00e9.", "N\u00e3o foi poss\u00edvel enviar a mensagem. O sistema est\u00e1 ocupado."),
    UNABLE_TO_SEND_MESSAGE_UNAVAILABLE1("Unable to send message - player unavailable.", "Deine Nachricht konnte nicht verschickt werden,", "Impossible d'envoyer un message - joueur indisponible.", "N\u00e3o foi poss\u00edvel enviar a mensagem. O jogador n\u00e3o est\u00e1 dispon\u00edvel."),
    UNABLE_TO_SEND_MESSAGE_UNAVAILABLE2(null, "der Spieler ist momentan nicht verf\u00fcgbar.", null, null),
    UNABLE_TO_SEND_MESSAGE_NOTFRIEND1("Unable to send message - player not on your friends list.", "Nachricht kann nicht geschickt werden,", "Impossible d'envoyer un message - joueur non inclus dans votre liste d'amis.", "N\u00e3o foi poss\u00edvel enviar a mensagem. O jogador n\u00e3o est\u00e1 na sua lista de amigos."),
    UNABLE_TO_SEND_MESSAGE_NOTFRIEND2(null, "Spieler nicht auf deiner Freunde-Liste.", null, null),
    UNABLE_TO_SEND_MESSAGE_PASSWORD_A("You appear to be telling someone your password - please don't!", "Willst du jemandem dein Passwort verraten? Das darfst du nicht! Falls das", "Il semble que vous r\u00e9v\u00e9liez votre mot de passe \u00e0 quelqu'un - ne faites jamais \u00e7a !", "Parece que voc\u00ea est\u00e1 revelando sua senha a algu\u00e9m. N\u00e3o fa\u00e7a isso!"),
    UNABLE_TO_SEND_MESSAGE_PASSWORD_B("If you are not, please change your password to something more obscure!", "nicht der Fall ist, \u00e4ndere dein Passwort zu einem ungew\u00f6hnlicheren Begriff!", "Si ce n'est pas le cas, remplacez votre mot de passe par une formule moins \u00e9vidente !", "Caso n\u00e3o esteja, altere sua senha para algo mais obscuro!"),
    UNABLE_TO_SEND_MESSAGE_NO_DISPLAYNAME_1("Unable to send message - set your display name first by logging into the game.", "Nachricht konnte nicht gesendet werden.  Bitte richte erst deinen Charakternamen ein, ", "Impossible d'envoyer le message - enregistrez un nom de personnage en vous connectant au jeu.", "N\u00e3o \u00e9 poss\u00edvel enviar a mensagem. Defina um nome de personagem antes, fazendo login no jogo."),
    UNABLE_TO_SEND_MESSAGE_NO_DISPLAYNAME_2(null, "indem du dich ins Spiel einloggst.", null, null),
    SNAPSHOT_BUFFER_EMPTY1("For that rule you can only report players who have spoken or traded recently.", "Mit dieser Option k\u00f6nnen nur Spieler gemeldet werden,", "Cette r\u00e8gle n'est invocable que pour les discussions ou \u00e9changes r\u00e9cents.", "Para essa regra, voc\u00ea s\u00f3 pode denunciar jogadores com quem tenha falado ou negociado recentemente."),
    SNAPSHOT_BUFFER_EMPTY2(null, "die k\u00fcrzlich gesprochen oder gehandelt haben.", null, null),
    NAMEDIALOG_NOTFOUND("That player is offline, or has privacy mode enabled.", "Dieser Spieler ist offline oder hat den Privatsph\u00e4ren-Modus aktiviert.", "Ce joueur est d\u00e9connect\u00e9 ou en mode priv\u00e9.", "O jogador est\u00e1 offline ou est\u00e1 com o modo de privacidade ativado."),
    UNABLE_TO_SEND_MESSAGE_QUICKCHAT1("You cannot send a quick chat message to a player on this world at this time.", "Einem Spieler auf dieser Welt k\u00f6nnen derzeit keine Direktchat-Nachrichten", "Impossible d'envoyer un message rapide \u00e0 un joueur de ce serveur \u00e0 l'heure actuelle.", "Voc\u00ea n\u00e3o pode enviar uma mensagem de papo r\u00e1pido para um jogador neste mundo neste momento."),
    UNABLE_TO_SEND_MESSAGE_QUICKCHAT2(null, "geschickt werden.", null, null),
    UNABLE_TO_SEND_MESSAGE_QUICKCHATWORLD1("This player is on a quick chat world and cannot receive your message.", "Der Spieler kann auf einer Direktchat-Welt keine Nachrichten empfangen.", "Ce joueur est sur un serveur \u00e0 messagerie rapide et ne peut pas recevoir votre message.", "Este jogador n\u00e3o pode receber sua mensagem porque est\u00e1 em um mundo de papo r\u00e1pido."),
    CHAT_DISABLED("Chat disabled", "Deaktiviert", "Messagerie d\u00e9sactiv\u00e9e", "Bate-papo desativado"),
    UNDER13_FRIENDSCHAT_PREFIX("friends_chat", "friends_chat", "friends_chat", "friends_chat"),
    UNABLE_TO_SEND_MESSAGE_NOT_IN_FRIENDS_CHAT("You are not currently in a friends chat channel.", "Du befindest dich derzeit nicht in einem Freundes-Chatraum.", "Vous ne faites pas partie d'un canal de discussion.", "No momento, voc\u00ea n\u00e3o est\u00e1 no bate-papo entre amigos."),
    UNABLE_TO_SEND_MESSAGE_FRIENDS_CHAT_TOO_LOW_RANK("You are not allowed to talk in this friends chat channel.", "Du darfst in diesem Freundes-Chatraum nicht reden.", "Vous n'\u00eates pas autoris\u00e9 \u00e0 parler dans ce canal de discussion.", "Voc\u00ea pode falar neste bate-papo entre amigos."),
    UNABLE_TO_SEND_MESSAGE_FRIENDS_CHAT_ERROR("Error sending message to friends chat - please try again later!", "Fehler beim Versenden der Nachricht - bitte versuch es sp\u00e4ter erneut.", "Erreur lors de l'envoi de ce message \u2013 veuillez r\u00e9essayer ult\u00e9rieurement !", "Erro ao enviar mensagem para bate-papo entre amigos - favor tentar novamente mais tarde!"),
    FRIENDS_CHAT_STILL_IN_CHANNEL("Please wait until you are logged out of your previous channel.", "Bitte warte, bis du den vorherigen Chatraum verlassen hast.", "Veuillez attendre d'\u00eatre d\u00e9connect\u00e9(e) de votre canal pr\u00e9c\u00e9dent.", "Aguarde at\u00e9 se desconectar do canal anterior."),
    FRIENDS_CHAT_NOT_IN_CHANNEL("You are not currently in a channel.", "Du befindest dich derzeit nicht in einem Chatraum.", "Vous n'\u00eates dans aucun canal \u00e0 l'heure actuelle.", "No momento voc\u00ea n\u00e3o est\u00e1 em um canal."),
    FRIENDS_CHAT_ATTEMPTING_JOIN("Attempting to join channel...", "Chatraum wird betreten...", "Tentative de connexion au canal...", "Tentando acessar canal..."),
    FRIENDS_CHAT_SENDING_LEAVE_REQ("Sending request to leave channel...", "Chatraum wird verlassen...", "Envoi de la demande de sortie du canal...", "Enviando solicita\u00e7\u00e3o para deixar o canal..."),
    FRIENDS_CHAT_JOIN_IN_PROGRESS("Already attempting to join a channel - please wait...", "Du versuchst bereits, einem Chatraum beizutreten - bitte warte.", "Tentative de connexion au canal d\u00e9j\u00e0 en cours - veuillez patienter...", "J\u00e1 h\u00e1 uma tentativa de entrar em um canal. Aguarde..."),
    FRIENDS_CHAT_LEAVE_IN_PROGRESS("Leave request already in progress - please wait...", "Du versuchst bereits, einen Chatraum zu verlassen - bitte warte.", "Demande de sortie d\u00e9j\u00e0 effectu\u00e9e - veuillez patienter...", "Solicita\u00e7\u00e3o de sa\u00edda j\u00e1 em andamento. Aguarde..."),
    FRIENDS_CHAT_INVALID_NAME("Invalid channel name entered!", "Ung\u00fcltiger Chatraum-Name angegeben.", "Nom de canal incorrect !", "Nome de canal inv\u00e1lido!"),
    FRIENDS_CHAT_NOT_AVAILABLE("Unable to join friends chat at this time - please try again later!", "Freundes-Chatraum kann nicht betreten werden - bitte versuch es sp\u00e4ter erneut.", "Vous ne pouvez pas rejoindre ce canal de discussion pour le moment - veuillez r\u00e9essayer ult\u00e9rieurement !", "N\u00e3o foi poss\u00edvel participar do bate-papo entre amigos - favor tentar novamente mais tarde!"),
    FRIENDS_CHAT_JOIN_SUCCESS_A("Now talking in friends chat channel ", "Freundes-Chatraum: ", "Vous participez actuellement au canal de discussion : ", "Falando no momento no bate-papo entre amigos: "),
    FRIENDS_CHAT_JOIN_SUCCESS_A_U13("Now talking in friends chat channel of player: ", "Freundes-Chat dieses Spielers beigetreten: ", "Vous participez actuellement au canal de discussion du joueur : ", "Falando no momento no bate-papo entre amigos do jogador: "),
    FRIENDS_CHAT_JOIN_ERROR("Error joining friends chat channel - please try again later!", "Fehler beim Betreten des Freundes-Chatraums - bitte versuch es sp\u00e4ter erneut.", "Erreur lors de la connexion au canal de discussion - veuillez r\u00e9essayer ult\u00e9rieurement !", "Erro ao participar do bate-papo entre-amigos - favor tentar novamente mais tarde!"),
    FRIENDS_CHAT_JOIN_ATTACKBLOCKED("You are temporarily blocked from joining channels - please try again later!", "Du darfst derzeit keine Chatr\u00e4ume betreten - bitte versuch es sp\u00e4ter.", "Vous \u00eates temporairement exclu des canaux - veuillez r\u00e9essayer ult\u00e9rieurement.", "Voc\u00ea est\u00e1 temporariamente impedido de entrar em canais. Tente de novo depois!"),
    FRIENDS_CHAT_JOIN_NOTEXIST("The channel you tried to join does not exist.", "Der von dir gew\u00fcnschte Chatraum existiert nicht.", "Le canal que vous essayez de rejoindre n'existe pas.", "O canal que voc\u00ea tentou acessar n\u00e3o existe."),
    FRIENDS_CHAT_JOIN_ROOMFULL("The channel you tried to join is currently full.", "Der von dir gew\u00fcnschte Chatraum ist derzeit \u00fcberf\u00fcllt.", "Le canal que vous essayez de rejoindre est plein.", "O canal que voc\u00ea tentou acessar est\u00e1 cheio no momento."),
    FRIENDS_CHAT_JOIN_LOWRANK("You do not have a high enough rank to join this friends chat channel.", "Dein Rang reicht nicht aus, um diesen Freundes-Chatraum zu betreten.", "Votre rang n'est pas assez \u00e9lev\u00e9 pour rejoindre ce canal de discussion.", "Voc\u00ea n\u00e3o tem uma classifica\u00e7\u00e3o alta o suficiente para participar deste bate-papo entre amigos."),
    FRIENDS_CHAT_JOIN_BANNED("You are temporarily banned from this friends chat channel.", "Du wurdest tempor\u00e4r von diesem Freundes-Chatraum gesperrt.", "Vous avez \u00e9t\u00e9 exclu temporairement de ce canal de discussion.", "Voc\u00ea foi temporariamente banido deste bate-papo entre amigos."),
    FRIENDS_CHAT_JOIN_IGNORELIST("You are not allowed to join this user's friends chat channel.", "Du darfst den Freundes-Chatraum dieses Benutzers nicht betreten.", "Vous n'\u00eates pas autoris\u00e9 \u00e0 rejoindre le canal de discussion de cet utilisateur.", "Voc\u00ea n\u00e3o pode participar do bate-papo entre amigos deste usu\u00e1rio."),
    FRIENDS_CHAT_USER_JOINED(" joined the channel.", " hat den Chatraum betreten.", " a rejoint le canal.", " entrou no canal."),
    FRIENDS_CHAT_USER_LEFT(" left the channel.", " hat den Chatraum verlassen.", " a quitt\u00e9 le canal.", " deixou o canal."),
    FRIENDS_CHAT_USER_KICKED(" was kicked from the channel.", " wurde aus dem Chatraum rausgeworfen.", " a \u00e9t\u00e9 expuls\u00e9 du canal.", " foi expulso do canal."),
    FRIENDS_CHAT_LEAVE_KICKED("You have been kicked from the channel.", "Du wurdest aus dem Chatraum rausgeworfen.", "Vous avez \u00e9t\u00e9 expuls\u00e9 du canal.", "Voc\u00ea foi expulso do canal."),
    FRIENDS_CHAT_LEAVE_REMOVED("You have been removed from this channel.", "Du wurdest aus dem Chatraum entfernt.", "Vous avez \u00e9t\u00e9 supprim\u00e9 de ce canal.", "Voc\u00ea foi retirado desse canal."),
    FRIENDS_CHAT_LEAVE_DEFAULT("You have left the channel.", "Du hast den Chatraum verlassen.", "Vous avez quitt\u00e9 le canal.", "Voc\u00ea saiu do canal."),
    FRIENDS_CHAT_ENABLED_A("Your friends chat channel has now been enabled!", "Dein Freundes-Chat ist jetzt eingeschaltet.", "Votre canal de discussion est maintenant activ\u00e9 !", "O seu bate-papo entre amigos foi ativado!"),
    FRIENDS_CHAT_ENABLED_B("Join your channel by clicking 'Join Chat' and typing: ", "Klick auf 'Betreten' und gib ein: ", "Pour rejoindre votre canal, cliquez sur \u00ab Participer \u00bb et entrez : ", "Para entrar no seu canal, clique em \"Acessar bate-papo\" e digite: "),
    FRIENDS_CHAT_DISABLED("Your friends chat channel has now been disabled!", "Dein Freundes-Chat ist jetzt ausgeschaltet.", "Votre canal de discussion est maintenant d\u00e9sactiv\u00e9 !", "O seu bate-papo entre amigos foi desativado!"),
    FRIENDS_CHAT_KICK_LOW_RANK("You do not have permission to kick users in this channel.", "Du darfst keine Benutzer aus diesem Chatraum rauswerfen.", "Vous n'\u00eates pas autoris\u00e9 \u00e0 expulser des utilisateurs de ce canal.", "Voc\u00ea n\u00e3o tem permiss\u00e3o para expulsar usu\u00e1rios neste canal."),
    FRIENDS_CHAT_KICK_USER_HIGHER("You do not have permission to kick this user.", "Du darfst diesen Benutzer nicht rauswerfen.", "Vous n'\u00eates pas autoris\u00e9 \u00e0 expulser cet utilisateur.", "Voc\u00ea n\u00e3o tem permiss\u00e3o para expulsar este usu\u00e1rio."),
    FRIENDS_CHAT_KICK_NOT_FOUND("That user is not in this channel.", "Dieser Benutzer befindet sich nicht in diesem Chatraum.", "Cet utilisateur n'est pas dans ce canal.", "Esse usu\u00e1rio n\u00e3o est\u00e1 no canal."),
    FRIENDS_CHAT_KICK_SUCCESS("Your request to kick/ban this user was successful.", "Der Rauswurf/die Sperrung war erfolgreich.", "Votre demande d'exclusion de ce joueur a \u00e9t\u00e9 accept\u00e9e.", "Seu pedido para expulsar/suspender este jogador foi bem sucedido."),
    FRIENDS_CHAT_KICK_SUCCESS_RESET("Your request to refresh this user's temporary ban was successful.", "Die Verl\u00e4ngerung der tempor\u00e4ren Sperrung dieses Spielers war erfolgreich.", "Le renouvellement d'exclusion temporaire de ce joueur a \u00e9t\u00e9 accept\u00e9.", "Seu pedido para reiniciar a suspens\u00e3o tempor\u00e1ria deste jogador foi bem sucedido."),
    MUTED_TEMPORARY("You have been temporarily muted due to breaking a rule.", "Aufgrund eines Regelversto\u00dfes wurdest du vor\u00fcbergehend stumm geschaltet.", "La messagerie instantan\u00e9e a \u00e9t\u00e9 temporairement bloqu\u00e9e suite \u00e0 une infraction.", "Voc\u00ea foi temporariamente vetado por ter violado uma regra."),
    MUTED_TEMPORARY_TIME_A("This mute will remain for a further ", "Diese Stummschaltung gilt f\u00fcr weitere ", "Votre acc\u00e8s restera bloqu\u00e9 encore ", "Este veto permanecer\u00e1 por mais "),
    MUTED_TEMPORARY_TIME_B(" days.", " Tage.", " jours.", " dias."),
    MUTED_TEMPORARY_1DAY("You will be un-muted within 24 hours.", "Du wirst innerhalb der n\u00e4chsten 24 Stunden wieder sprechen k\u00f6nnen.", "Vous aurez \u00e0 nouveau acc\u00e8s \u00e0 la messagerie instantan\u00e9e dans 24 heures.", "O veto ser\u00e1 retirado dentro de 24 horas."),
    MUTED_PREVENT("To prevent further mutes please read the rules.", "Um eine erneute Stummschaltung zu verhindern, lies bitte die Regeln.", "Pour \u00e9viter un nouveau blocage, lisez le r\u00e8glement.", "Para evitar outros vetos, leia as regras."),
    MUTED_PERMANENT("You have been permanently muted due to breaking a rule.", "Du wurdest permanent stumm geschaltet, da du gegen eine Regel versto\u00dfen hast.", "L'acc\u00e8s \u00e0 la messagerie instantan\u00e9e vous a d\u00e9finitivement \u00e9t\u00e9 retir\u00e9 suite \u00e0 une infraction.", "Voc\u00ea foi permanentemente vetado por ter violado uma regra."),
    LOADING("Loading - please wait.", "Ladevorgang - bitte warte.", "Chargement en cours. Veuillez patienter.", "Carregando. Aguarde."),
    PROFILING("Profiling...", "Profiling...", "Profilage...", "Profiling..."),
    CONLOST("Connection lost.", "Verbindung abgebrochen.", "Connexion perdue.", "Conex\u00e3o perdida."),
    ATTEMPT_TO_REESTABLISH("Please wait - attempting to reestablish.", "Bitte warte - es wird versucht, die Verbindung wiederherzustellen.", "Veuillez patienter - tentative de r\u00e9tablissement.", "Tentando reestabelecer conex\u00e3o. Aguarde."),
    CHECKING_FOR_UPDATES("Checking for updates - ", "Suche nach Updates - ", "V\u00e9rification des mises \u00e0 jour - ", "Verificando atualiza\u00e7\u00f5es - "),
    DOWNLOADING_UPDATES("Fetching Updates - ", "Lade Update - ", "Chargement des MAJ - ", "Carregando atualiza\u00e7\u00f5es - "),
    MAINLOAD110("Loading config - ", "Lade Konfiguration - ", "Chargement des fichiers config - ", "Carregando config - "),
    MAINLOAD110B("Loaded config", "Konfig geladen.", "Fichiers config charg\u00e9s", "Config carregada"),
    MAINLOAD120("Loading sprites - ", "Lade Sprites - ", "Chargement des sprites - ", "Carregando sprites - "),
    MAINLOAD120B("Loaded sprites", "Sprites geladen.", "Sprites charg\u00e9s", "Sprites carregados"),
    MAINLOAD130("Loading wordpack - ", "Lade Wordpack - ", "Chargement du module texte - ", "Carregando pacote de palavras - "),
    MAINLOAD130B("Loaded wordpack", "Wordpack geladen.", "Module texte charg\u00e9", "Pacote de palavras carregado"),
    MAINLOAD140("Loading interfaces - ", "Lade Benutzeroberfl\u00e4che - ", "Chargement des interfaces - ", "Carregando interfaces - "),
    MAINLOAD140B("Loaded interfaces", "Benutzeroberfl\u00e4che geladen.", "Interfaces charg\u00e9es", "Interfaces carregadas"),
    MAINLOAD150("Loading interface scripts - ", "Lade Interface-Skripte - ", "Chargement des interfaces - ", "Carregando interfaces - "),
    MAINLOAD150B("Loaded interface scripts", "Interface-Skripte geladen", "Interfaces charg\u00e9es", "Interfaces carregadas"),
    MAINLOAD160("Loading additional fonts - ", "Lade Zusatzschriftarten - ", "Chargement de polices secondaires - ", "Carregando fontes principais - "),
    MAINLOAD160B("Loaded additional fonts", "Zusatzschriftarten geladen", "Polices secondaires charg\u00e9es", "Fontes principais carregadas"),
    MAINLOAD170("Loading world map - ", "Lade Weltkarte - ", "Chargement de la mappemonde - ", "Carregando mapa-m\u00fandi - "),
    MAINLOAD170B("Loaded world map", "Weltkarte geladen", "Mappemonde charg\u00e9e", "Mapa-m\u00fandi carregado"),
    MAINLOAD180("Loading world list data", "Lade Liste der Welten", "Chargement de la liste des serveurs", "Carregando dados da lista de mundos"),
    MAINLOAD180B("Loaded world list data", "Liste der Welten geladen", "Liste des serveurs charg\u00e9e", "Dados da lista de mundos carregados"),
    MAINLOAD190B("Loaded client variable data", "Client-Variablen geladen", "Variables du client charg\u00e9es", "As vari\u00e1veis do sistema foram carregadas"),
    LOADINGDOTDOTDOT("Loading...", "Lade...", "Chargement en cours...", "Carregando..."),
    SNAPSHOT_PLEASECLOSE1("Please close the interface you have open before using 'Report Abuse'.", "Bitte schlie\u00df die momentan ge\u00f6ffnete Benutzeroberfl\u00e4che,", "Fermez l'interface que vous avez ouverte avant d'utiliser le bouton \u00ab Signaler un abus \u00bb.", "Feche a interface aberta antes de usar o recurso \"Denunciar abuso\"."),
    SNAPSHOT_PLEASECLOSE2(null, "bevor du die Option 'Regelversto\u00df melden' benutzt.", null, null),
    SYSTEMUPDATE("System update in: ", "System-Update in: ", "Mise \u00e0 jour syst\u00e8me dans : ", "Atualiza\u00e7\u00e3o do sistema em: "),
    FRIENDLOGIN(" has logged in.", " loggt sich ein.", " s'est connect\u00e9.", " entrou no jogo."),
    FRIENDLOGOUT(" has logged out.", " loggt sich aus.", " s'est d\u00e9connect\u00e9.", " saiu do jogo."),
    UNABLETOFIND("Unable to find ", "Spieler kann nicht gefunden werden: ", "Impossible de trouver ", "N\u00e3o \u00e9 poss\u00edvel encontrar "),
    USE("Use", "Benutzen", "Utiliser", "Usar"),
    EXAMINE("Examine", "Untersuchen", "Examiner", "Examinar"),
    ATTACK("Attack", "Angreifen", "Attaquer", "Atacar"),
    CHOOSEOPTION("Choose Option", "W\u00e4hl eine Option", "Choisir une option", "Selecionar op\u00e7\u00e3o"),
    MOREOPTIONS(" more options", " weitere Optionen", " autres options", " mais op\u00e7\u00f5es"),
    WALKHERE("Walk here", "Hierhin gehen", "Atteindre", "Caminhar para c\u00e1"),
    FACEHERE("Face here", "Hierhin drehen", "Regarder dans cette direction", "Virar para c\u00e1"),
    LEVEL("level: ", "Stufe: ", "niveau ", "n\u00edvel: "),
    SKILL("skill: ", "Fertigkeit: ", "comp\u00e9tence ", "habilidade: "),
    RATING("rating: ", "Kampfstufe: ", "classement ", "qualifica\u00e7\u00e3o: "),
    PLEASEWAIT("Please wait...", "Bitte warte...", "Veuillez attendre", "Aguarde..."),
    CLOSE("Close", "Bitte schlie\u00df die momentan ge\u00f6ffnete Benutzeroberfl\u00e4che,", "Fermez l'interface que vous avez ouverte avant d'utiliser le bouton \u00ab Signaler un abus \u00bb.", "Feche a interface aberta antes de usar o recurso \"Denunciar abuso\"."),
    MINISEPERATOR(" ", ": ", " ", " "),
    MILLION("M", "M", "M", "M"),
    MILLION_SHORT("M", "M", "M", "M"),
    THOUSAND("K", "T", "K", "K"),
    THOUSAND_SHORT("K", "T", "K", "K"),
    FROM("From", "Von:", "De", "De"),
    SELF("Self", "Mich", "Moi", "Eu"),
    FRIENDLISTDUPE(" is already on your friends list.", " steht bereits auf deiner Freunde-Liste!", " est d\u00e9j\u00e0 dans votre liste d'amis.", " j\u00e1 est\u00e1 na sua lista de amigos."),
    IGNORELISTFULL("Your ignore list is full. Max of 100 users.", "Deine Ignorieren-Liste ist voll, du kannst nur 100 Spieler darauf eintragen.", "Votre liste noire est pleine (100 noms maximum).", "Sua lista de ignorados est\u00e1 cheia. O limite \u00e9 100 usu\u00e1rios."),
    IGNORELISTDUPE(" is already on your ignore list.", " steht bereits auf deiner Ignorieren-Liste!", " est d\u00e9j\u00e0 dans votre liste noire.", " j\u00e1 est\u00e1 na sua lista de ignorados."),
    FRIENDCANTADDSELF("You can't add yourself to your own friends list.", "Du kannst dich nicht auf deine eigene Freunde-Liste setzen!", "Vous ne pouvez pas ajouter votre nom \u00e0 votre liste d'amis.", "Voc\u00ea n\u00e3o pode adicionar a si pr\u00f3prio \u00e0 sua lista de amigos."),
    IGNORECANTADDSELF("You can't add yourself to your own ignore list.", "Du kannst dich nicht auf deine eigene Ignorieren-Liste setzen!", "Vous ne pouvez pas ajouter votre nom \u00e0 votre liste noire.", "Voc\u00ea n\u00e3o pode adicionar a si pr\u00f3prio \u00e0 sua lista de ignorados."),
    FRIENDLIST_TIMED_SAVE("Changes will take effect on your friends chat in the next 60 seconds.", "Die \u00c4nderungen am Freundes-Chat werden innerhalb von 60 Sekunden \u00fcbernommen.", "Les modifications seront apport\u00e9s \u00e0 votre canal de discussion dans les 60 prochaines secondes.", "Mundan\u00e7as v\u00e3o ocorrer em seu bate-papo entre amigos nos pr\u00f3ximos 60 segundos."),
    REMOVEIGNORE1("Please remove ", "Bitte entferne ", "Veuillez commencer par supprimer ", "Remova "),
    REMOVEIGNORE2(" from your ignore list first.", " zuerst von deiner Ignorieren-Liste!", " de votre liste noire.", " da sua lista de ignorados primeiro."),
    REMOVEFRIEND1("Please remove ", "Bitte entferne ", "Veuillez commencer par supprimer ", "Remova "),
    REMOVEFRIEND2(" from your friends list first.", " zuerst von deiner Freunde-Liste!", " de votre liste d'amis.", " da sua lista de amigos primeiro."),
    CHATCOL0("yellow:", "gelb:", "jaune:", "amarelo:"),
    CHATCOL1("red:", "rot:", "rouge:", "vermelho:"),
    CHATCOL2("green:", "gr\u00fcn:", "vert:", "verde:"),
    CHATCOL3("cyan:", "blaugr\u00fcn:", "cyan:", "cyan:"),
    CHATCOL4("purple:", "lila:", "violet:", "roxo:"),
    CHATCOL5("white:", "weiss:", "blanc:", "branco:"),
    CHATCOL6("flash1:", "blinken1:", "clignotant1:", "flash1:"),
    CHATCOL7("flash2:", "blinken2:", "clignotant2:", "flash2:"),
    CHATCOL8("flash3:", "blinken3:", "clignotant3:", "brilho3:"),
    CHATCOL9("glow1:", "leuchten1:", "brillant1:", "brilho1:"),
    CHATCOL10("glow2:", "leuchten2:", "brillant2:", "brilho2:"),
    CHATCOL11("glow3:", "leuchten3:", "brillant3:", "brilho3:"),
    CHATEFFECT1("wave:", "welle:", "ondulation:", "onda:"),
    CHATEFFECT2("wave2:", "welle2:", "ondulation2:", "onda2:"),
    CHATEFFECT3("shake:", "sch\u00fctteln:", "tremblement:", "tremor:"),
    CHATEFFECT4("scroll:", "scrollen:", "d\u00e9roulement:", "rolagem:"),
    CHATEFFECT5("slide:", "gleiten:", "glissement:", "deslizamento:"),
    UNKNOWN_FRIEND_DISPLAYNAME_PLACEHOLDER("Friend", "Freund", "Ami", "Amigo");
    
    private final Map fc = new HashMap(7);

    public static String g(Mk163 mk163, Language language) {
        return (String)mk163.fc.get(language);
    }

    private Mk163(String string2, String string3, String string4, String string5) {
        this.fc.put(Language.EN, string2);
        this.fc.put(Language.DE, string3);
        this.fc.put(Language.FR, string4);
        this.fc.put(Language.PT, string5);
    }
}

