package rs2.client.login;

enum L606 {
   WAIT_FOR_HOP_BLOCK_DURATION,
   CONNECT_UDP,
   SEND_LOGIN_REQUEST,
   DELAY,
   WAIT_FOR_LOGIN_RESPONSE,
   WAIT_FOR_CONNECTION_ACK,
   WAIT_FOR_QUEUE_POSITION,
   WAIT_FOR_UDP_LOGIN,
   CONNECT_TCP,
   WAIT_FOR_LOGIN_DETAILS,
   WAIT_FOR_SCRIPT_DISALLOW_REASON,
   WAIT_FOR_PLAYER_PACKET,
   WAIT_FOR_PLAYER_PACKET_LENGTH1,
   WAIT_FOR_LOGIN_OK_LENGTH,
   WAIT_FOR_UDP_LOGIN_RECONNECT,
   WAIT_FOR_PLAYER_PACKET_LENGTH2;
}
