package rs2.client.login;

enum Q580 {
   WAIT_FOR_CONNECTION_ACK,
   WAIT_FOR_SSO_KEY_RESPONSE,
   CONNECT,
   WAIT_FOR_SSO_KEY,
   WAIT_FOR_SOCIAL_NETWORK_TOKEN,
   WAIT_FOR_SOCIAL_NETWORK_TOKEN_LENGTH;
}
