/*
 * Decompiled with CFR 0.146.
 */
package rs2.client.login;

enum Q580 {
    CONNECT,
    WAIT_FOR_CONNECTION_ACK,
    WAIT_FOR_SOCIAL_NETWORK_TOKEN_LENGTH,
    WAIT_FOR_SOCIAL_NETWORK_TOKEN,
    WAIT_FOR_SSO_KEY_RESPONSE,
    WAIT_FOR_SSO_KEY;
    
}

